### ISSUE TITLE
X-PJAX is X-Pjax

### ISSUE THREAD

**Issue by littke** [defunkt/jquery-pjax#10]
Hey.

Both Chrome dev and Firefox 4.0 seem to be converting the name of the header to X-Pjax, so looking for X-PJAX serverside didn't work for me.

**Comment by Mstafamhamadmhamad** [comment]
> Hey.
> 
> Both Chrome dev and Firefox 4.0 seem to be converting the name of the header to X-Pjax, so looking for X-PJAX serverside didn't work for me.
