### ISSUE TITLE
Append Data to PJAX Request

### ISSUE THREAD

**Issue by kevinswarner** [defunkt/jquery-pjax#131]
I have a few questions about PJAX usage and capabilities...
- Can you change the ajax type to "POST" in the beforeSend handler? I cannot figure out a good way to do this.
- Can you change the content type of the ajax request to "application/json"?
- Can you append data paramters to the ajax request?

My goal is to catch each PJAX request and append some data (an array of objects) to the request. I send ajax requests all the time and do this, but I am having issues figuring out how to modify the PJAX request to do this.

Any help greatly appreciated.

**Comment by claudiogg88** [comment]
can i change from "GET" to a "POST" ?? before send? 

    if (options.type.toLowerCase() === "get") {

            options.type = "POST";

            var tipo = $("#estadistica-tipo").val();
            var extraGlobalStr = "&Extra[]=" + extraGlobal.join("&Extra[]=");
            options.data = encodeURI("Tipo=" + tipo + extraGlobalStr)+"&_pjax=%23detalle-pjax";

        }
not working...

**Comment by Danillaa** [comment]
settings.data not exists
