### ISSUE TITLE
pjax scrolls to top by default

### ISSUE THREAD

**Issue by staabm** [defunkt/jquery-pjax#133]
is it intended behaviour, that on each pjax request the browser scrolls to top?

the reason for this is that scrollTo defaults to 0 instead of false

```

pjax.defaults = {
  timeout: 650,
  push: true,
  replace: false,
  type: 'GET',
  dataType: 'html',
  scrollTo: 0,
  maxCacheLength: 20
}

```

**Comment by almirb** [comment]
Hello!

Why the scrollTo defaults are different in Yii Pjax widget and jquery.pjax.js?

http://www.yiiframework.com/forum/index.php/topic/71190-difference-between-pjax-defaults-php-widget-and-jquery/
