### ISSUE TITLE
callback on back button

### ISSUE THREAD

**Issue by digitalplaywright** [defunkt/jquery-pjax#152]
I apologize if this is not the correct forum for this question. We use pjax to load the contents of a modal, and then we launch the modal with the 'pjax:end' callback. However,  the browser back button renders the previous page with the modal still overlaying the page. Please let us know if you have any recommendations on how to best create a callback on the browser back button to close the modal.

**Comment by lustremedia** [comment]
@bkabka Thanks for the pointer I think that is going to work.

**Comment by hmayer00** [comment]
Check out https://github.com/defunkt/jquery-pjax/issues/469, which is basically the same issue.  It has a commit attached that should fix this: 247b255d51b1caee3b8bacacc9009408f2b8ac89.
