### ISSUE TITLE
Load js function on load

### ISSUE THREAD

**Issue by mirzadelic** [defunkt/jquery-pjax#181]
I use pjax, and everything works, but 1 thing.
When i load content, and js with it, js on load works, but function like this:

``` javascript
var map = {
    init : function() {
        alert('test');
    }

}

map.init
```

that function is not calling, and ther regular `function test() { ... }` doesn't work too, why ?

**Comment by fari-99** [comment]
haha, still not understand this. everything works fine, but the js do not load, only response content and title. btw @sagarsane can you explain to me what this issue is? need this.
