### ISSUE TITLE
HTTP caching 

### ISSUE THREAD

**Issue by eugenemiretsky** [defunkt/jquery-pjax#212]
Hi,
The URL is used to request a partial Pjax page and a full page, therefor both response will be cached under the same key. This will clearly lead to errors as the partial might get loaded instead of the full page and vis versa.

YUI provides a addPjaxParam options to add pjax=1 to the actual query url. is it possible to do the same in jquery-pjax?

**Comment by catmanjan** [comment]
Not sure if something has changed recently, but the _pjax parameter is passed in with the AJAX request, but it is not appended the browser URL which means both PJAX and non-PJAX requests are cached as the same page.

In our application this is resulting in errors as the PJAX request renders a partial response (excludes head and such)
