### ISSUE TITLE
"Uncaught $.fn.pjax or $.pjax.click requires an anchor element"

### ISSUE THREAD

**Issue by mattfordham** [defunkt/jquery-pjax#222]
Hey there. I am using 1.2 and can't seem to get things working at all. I get above error upon clicking a link (for a brief moment), and then the page loads as normal.

Here is how I am setting things up:

```
$('#main').pjax('a').on('pjax:send', function(){
    $(this).showLoader()
})
```

**Comment by christophwolff** [comment]
@josh i have the same error. How do i configure the server? There is only something with rails in the README. I have a PHP Setup in Wordpress. Thanks
