### ISSUE TITLE
Reinitalize javascripts on back button

### ISSUE THREAD

**Issue by tzoro** [defunkt/jquery-pjax#235]
Hi all, I'm having issue implementing pjax. Already checked stackowerflow and this issues board but i did not find solution.

I'm loading page first time full with all script's and every next request just load new content via Ajax. Basic pjax implementation in one container.

```
    $(document).on('click', 'a', function(event) {
        var container = document.getElementById('newContent');
        $.pjax.click(event, {container:container,timeout:2000});
    });
```

The problem is: Scripts like jQueryUI datepicker, checkbox, etc... doesn't reinitalize after user click on back button. I even tried iterate over that elements on window popstate event and reinitialize it again but with no success yet. 

I'm trying to do something like this...
1. initialize datepicker like: window.myDatepicker =  $('#datepicker).datepicker();
2. surf page little bit, build up history
3. hit back button, and get that datepicker via window.myDatepicker and reinitalize it or refresh, but it doesn't work.

Do i have to care about js initalizations at first like to put them on window scope or just initalize it like usual $('#datepicker).datepicker(). Is there some pattern to implement pjax that make possible to interact (for real) with elements on popstate event ?

Thank you !

**Comment by hmayer00** [comment]
Check out https://github.com/defunkt/jquery-pjax/issues/469, which is basically the same issue.  It has a commit attached that should fix this: 247b255d51b1caee3b8bacacc9009408f2b8ac89.
