### ISSUE TITLE
version number in jquery.pjax.js?

### ISSUE THREAD

**Issue by jwfearn** [defunkt/jquery-pjax#272]
There's a version specified in component.json.  For those of us not using Bower, would consider putting a version indicator of some sort in jquery.pjax.js itself as well?  A comment would be fine.

**Comment by dongwq** [comment]
+2^1024

**Comment by mislav** [comment]
Sorry, I don't want to maintain version numbers in two separate places.

If you want to check whether you have the latest version of pjax in your app, simply download the latest `jquery.pjax.js`, overwriting the one in your application, then use `git diff` to inspect changes. With this process you can even ride the edge version from master without waiting for tagged releases.
