### ISSUE TITLE
problem loading PJAX content in JSP page

### ISSUE THREAD

**Issue by kokujin** [defunkt/jquery-pjax#276]
I have a JSP page that generates several elements including the DIV that the PJAX content is supposed to be rendered in. How can I in one swoop:

Call the JSP page that generates the HTML page incuding the DIV that PJAX is supposed to be rendered in, and then the real PJAX  call that renders the content in the div created by the JSP beforehand.

Thanks

**Comment by samdark** [comment]
Can be closed since it's not really possible to get what's being asked.

**Comment by mislav** [comment]
Yeah, sorry this hasn't got any attention. I'm not really sure what's being asked here, so closing.
