### ISSUE TITLE
Pjax send fires twice

### ISSUE THREAD

**Issue by mshawCS** [defunkt/jquery-pjax#278]
I believe I ran into an issue that this user here tried to report:
https://github.com/defunkt/jquery-pjax/issues/245

I am doing some css transitions so it was more noticeable. Steps to reproduce are as follows:
1. Create a page that have the same navigation items and the pjax realted pages to load the content for those nav pages. I have a top level nav that is just replacing content in a div with an ID. 
2. Put a break point when viewing sources in chrome inside the $(document).on('pjax:send', function() { }
3. First click of a link only fires pjax:send once. 
4. Click on nav items and pjax:send fires twice. 

Also I made sure these are not binding twice from code I created.

**Comment by MarcosMenegazzo** [comment]
You were right. The problem were a "N-bound", not related to jquery-pjax. To avoid this behavior:

```javascript
$(document).on("ready", function(){ 
    /* 1 time setups, pjax for instance */
});
$(document).on("pjax:success", function(){
    // other setups, like ui components that need to be initialized after a pjax request/response
    // caution: pjax setup here will N-bound.
});
```
