### ISSUE TITLE
$.pjax.submit on a GET form duplicates parameters

### ISSUE THREAD

**Issue by bentappin** [defunkt/jquery-pjax#279]
I understand this feature is currently experimental.

Given a form like this:

``` html
<form action="" method="GET" class="form-search" data-pjax>
    <input id="id_search" name="search" type="text">
    <button type="submit" class="btn">Search</button>
</form>
```

And some JS like this:

``` javascript
$(document).on('submit', 'form[data-pjax]', function(event) {
  $.pjax.submit(event, '#pjax-container');
});
```

Performing multiple searches results in the URL building up with multiple `search` parameters. For example:
- /?search=first+search
- /?search=first+search&search=second+search

This is problematic because we're just hoping that the correct parameter gets pulled out server side.

**Comment by tdhooper** [comment]
This solution doesn't work if you need to preserve other parameters.

**Comment by dzona** [comment]
@sqs 's workaround did not work for me, as had to reload container which is not tied to single form submission. So I made following code snippet to solve my issue.

```
function removeDuplicateUrlParams(url) {
	var params = new URLSearchParams(url);
	var result = {},
		isArrayKey,
		arrayKey,
		prevArrayKey = '';

	for (var p of params.entries()) {
		isArrayKey = p[0].indexOf('[]', p[0].length - 2) !== -1;
		if (isArrayKey) {
			arrayKey = p[0].substr(0, p[0].length - 2);
			if (arrayKey === prevArrayKey) {
				result[arrayKey].push(p[1]);
			} else {
				result[arrayKey] = [p[1]];
			}
			prevArrayKey = arrayKey;
		} else {
			result[p[0]] = p[1];
			prevArrayKey = '';
		}
	}

	return $.param(result);
}

var search = removeDuplicateUrlParams(window.location.search);
var url = window.location.origin + window.location.pathname + '?' + search;

$.pjax.reload({
    container:'#pjax-container-id',
    url: url
});
```

**UPDATE**
or attach it globally, to every pjax request, and to handle additional params that can be passed to `$.pjax.reload()`.

```
$(document).on('pjax:beforeSend', function (event, xhr, options) {
    var url = new URL(options.url) || null;
	if (url && url.search) {
		options.url = url.origin + url.pathname + '?' + removeDuplicateUrlParams(url.search);
	}

	return true;
});
```
Not sure if params stacking is expected behavior, why it isn't handled by `pjax`? We should clean `window.location.href` for duplicate prams, when defaulting it imho.
