### ISSUE TITLE
Pjax does not work with subdomains

### ISSUE THREAD

**Issue by ghost** [defunkt/jquery-pjax#313]
Exemple : 

site.com/user/list/ , click on a user name that links to : user.site.com : it won't be a pjax request, even if this is the same main domain.

Can this be configured ?

**Comment by HasnBatal** [comment]
any progress in subdomin?

**Comment by Ziggizag** [comment]
In case of CORS issues the only reliable solution is CORS proxy:

https://github.com/cowboy/php-simple-proxy
