### ISSUE TITLE
Body class is lost for first page load

### ISSUE THREAD

**Issue by exbm** [defunkt/jquery-pjax#320]
When the page initially loads and you build the first pjax.state object; the bodyClass is not stored. When you navigate away from the home page and then back, to the homepage, the body class is left on second page messing up some css.

Fix: store the bodyCLass property on the inital pjax.state object

**Comment by mislav** [comment]
Sorry, but this is application logic that you'll need to solve in your own app. Pjax doesn't know about your body classes. See discussion in #493 for pointers
