### ISSUE TITLE
Control scrolling of window from server

### ISSUE THREAD

**Issue by imbolc** [defunkt/jquery-pjax#342]
For some cases (for example when form submited with pjax returns errors) will be better prevent window scrolling. May be use 'X-PJAX-NoScroll' server header for this?

Now i use next hack:

    $(document).on('submit', 'form[data-pjax]', function(event) {
        // keep window scroll position
        $.pjax.submit.prev = {
            top: $(window).scrollTop(),
            url: window.location.href
        };
        $.pjax.submit(event, '#pjax-container')
    });
    
    
    $(document).on('ready pjax:success', function () {
        // restore window scroll position
        var prev = $.pjax.submit.prev;
        if (prev && prev.url == window.location.href) {
            $(window).scrollTop(prev.top);
        }
        delete $.pjax.submit.prev;
    });

**Comment by mislav** [comment]
No, sorry. I don't think a HTTP header is a good solution for this. The best way to solve this would be with a `pjax:end` event handler in your app that controls scrolling based on the current contents of the page.
