### ISSUE TITLE
How to load page-specific javascript after pjax request completes

### ISSUE THREAD

**Issue by joshgarwood** [defunkt/jquery-pjax#365]
Hi there!

I am running into an issue where I need to load javascript that is specific to the page that I'm loading through pjax.  The scenario is as follows:
- Go to home page (all javascript tags are positioned directly above the closing 'body' tag).
- Navigate to the user profile page via pjax.  The content loads fine, but at this point I would like to load my "pages.profile.js" file.  I suppose this could be done by including the `<script>` tag in the page that gets loaded (profile page in this case), but then I'd end up with a `<script>` tag in the middle of my HTML, which seems pretty dirty.

So, I supposed what I'm wondering is, does pjax offer a way to dynamically load javascript files once the page content has been retrieved?  I'm using ASP.NET MVC and this is typically done with <a href="http://stackoverflow.com/questions/13660868/how-to-include-script-bundle-in-scripts-section-in-view">sections</a>.

Thanks!

**Comment by Christian1998** [comment]
I had the same problem. I just added an ID to the Script-Block (`<script id="page">`) and added it to the selectors (`selectors: ["script#page"]`)
Maybe it helps someone :)
