### ISSUE TITLE
Search input automatic blurring can't be stopped

### ISSUE THREAD

**Issue by valscion** [defunkt/jquery-pjax#377]
I'm writing a search widget which is used to update content next to it. When my search gets triggered, my text input field loses it's focus automatically, degrading user experience badly.

This is apparently intended behavior (see https://github.com/defunkt/jquery-pjax/commit/ef764ec671ff6fec8b7b42ec87c7dfe38084e6cc) but I'd really much like to see even a configurable option to disable this.

If you also believe that this should be configurable, I can implement it and supply a PR for you. Should you need any additional information, or more reasons on why this should   be done, I'll be happy to provide more input.

**Comment by mikrogroove** [comment]
I can't help with a PR, but this is how I prevent elements outside the PJAX container from losing focus. 

Change

    try {
      document.activeElement.blur()
    } catch (e) { }

to

    if($.contains(container, document.activeElement)) {
      try {
        document.activeElement.blur()
      } catch (e) { }
    }

Hopefully someone finds this useful.
