### ISSUE TITLE
Using fragment data-title tag for title submission

### ISSUE THREAD

**Issue by lustremedia** [defunkt/jquery-pjax#382]
I have seen that through #57 there was a `data-title` attribute introduced in order to update `<head><title>` when loading fragments. Is this somewhere documented and how do I get it to work?
Currently I try `<div data-title="My Fragment Title"></div>`, and I was hoping that pjax would pull my title out of the div in my fragment ... this is not the case. `<title>` in the fragment does work.
Can anyone help me out here?

**Comment by richgcook** [comment]
I know this is old but for some reason Wordpress doesn't take so kindly to using the data-title... just seems to ignore it. Works in Processwire. Who knows!
