### ISSUE TITLE
form submit: filter values on submit event

### ISSUE THREAD

**Issue by staabm** [defunkt/jquery-pjax#398]
I would like to filter some values before pjax submits them. ATM the only way to achieve that is to remove the related input-fields from the DOM, which is rather expensive.

```
$(document).on('submit', 'form', function(event) {
 var container = $(this).closest('[data-pjax-container]')

 // XXX filter values here
 $(this).find(":input").filter(function () {
   return $.trim(this.value).length == 0
 }).remove();

 $.pjax.submit(event, container)
})
```

Is there a "better way" to achieve that?

**Comment by staabm** [comment]
Thanks for your snippet, but it doesn't work for me. `settings.data` is undefined at that point and re-assigning it makes no difference.

> But the best way to handle your situation is to configure your server to serve pjax form submits even if all form fields were submitted, just as it handles a native form submit. Then you don't have to resort to hacks like this.

my actual issue is, that I get an ugly url with lots of empty params. my server is able both cases, no matter empty params are provided or not.

**Comment by staabm** [comment]
@mislav would you accept a PR which makes your posted example work?

**Comment by mislav** [comment]
Sure, if something is broken then please do fix it. I'd like to know why it doesn't work.

**Comment by staabm** [comment]
The underlying issue seems to be that, jquery doesn't pass `settings.data` into `beforeSend` when `type=GET`, see http://jsbin.com/juvarefubi/1/

side-note: the example above uses `ajax:beforeSend` but should use `pjax:beforeSend`

**Comment by staabm** [comment]
per https://github.com/jquery/jquery/issues/2081 a `beforeSend` handler is not the right point to modify the data.
It was suggested to use `prefilter` instead. I will check that.

**Comment by staabm** [comment]
@mislav the prefilter supposed by the jquery-guys doesnt sound like a good solution, because it will be attached to _every_ ajax request sent.

What do you think about introducing a event/callback to allow modification of data?

**Comment by staabm** [comment]
@mislav found a way how to solve my problem:

```	
$(document)
.on('submit', 'form[data-pjax]', function(event) {
      var $form = $(this);
	  var selector = $form.data('pjax');
	  var options = {};
	  options.data = $form.find(":input[value!='']").serializeArray();
	  $.pjax.submit(event, selector, options);
})
```

**Comment by staabm** [comment]
just updated the above code to filter the values only on GET, because it otherwise breaks POST processing
