### ISSUE TITLE
PJAX doesn't correctly mark links visited on IE

### ISSUE THREAD

**Issue by mikkotikkanen** [defunkt/jquery-pjax#452]
Navigate a site that uses a:visited colors and the visited selectors don't trigger.

It seems that IE requires `event.returnValue = false` in order to set the link as visited. Also, IE still seems to mark the links on reloads (F5) and not just hitting back button using History API.

**Comment by jschill** [comment]
Same in IE10 (emulated in IE11).

**Comment by mislav** [comment]
Thanks for everyone's reports. Does anyone have an idea how we can cancel the original click event on link (preventing them from being followed natively) but still have them marked as "visited" in IE?

**Comment by jschill** [comment]
Trying to get some attention from Microsoft regarding this.

https://connect.microsoft.com/IE/feedback/details/1187872/visited-is-not-activated-on-links-using-history-pushstate
Feel free to watch and comment on it.
