### ISSUE TITLE
requests aborted

### ISSUE THREAD

**Issue by slampis** [defunkt/jquery-pjax#46]
I am often getting requests aborted in Firefox and Google Chrome.
I tried to debug this and found this piece of code

```
    if ( xhr && xhr.readyState < 4) {
        xhr.onreadystatechange = $.noop
        xhr.abort()
    }
```

which makes perfectly sense but the requested aborted problem occurs also if there isn't another request pending.
I verified this with this code

```
    if ( xhr && xhr.readyState < 4) {
        alert('already pjaxing...');
    }
```

The popup isn't shown but the request often gets aborted. Server side everything works fine.
Any idea about this behaviour?

**Comment by FrankFan** [comment]
I was experiencing the same problem.
but `$.pjax.defaults.timeout = 5000` I've tried to use this line of code, still didn't work.

My situation is:
1. I use jstree with pjax to load file 
2. when I first time to click, there was 2 requests,  and the first one was canceled,
3. when I second time to click, there was 3 requests, the first and the second request was canceled too
4. the same way, when I thrid time to click, there was 4 requests, and the first 3 request was canceled too.

My Opioion:
fist I thouth it maybe something wrong with my event bind multiple times, and I use `jqury.off('click)`, 
the problem still exists.

Anyone can help me analysis what's wrong with my code ?

code:
```javascript
$jstree.on("select_node.jstree", function(e, data) {
        if (data && data.node && data.node.data == 'tree') {
                  // do normal ajax request
        } else { // blob 
                // pjax here
                $(document).pjax('nav a.jstree-clicked', '#tree-content-holder', {fragment:'#tree-content-holder', timeout:9000});
       }
});

```

**Comment by razamehdi-vteams** [comment]
@defunkt can you just give an example on how to set options for a pjax request. i understand we can set it like this:

$.pjax.defaults.timeout = 5000

but how can we set in this?

$(document).pjax('a#contentlink','#pjax-container');

**Comment by mislav** [comment]
@razamehdi-vteams [See README](https://github.com/defunkt/jquery-pjax#arguments):

```js
$(document).pjax('a#contentlink', {
  timeout: 5000,
  container: '#pjax-container'
})
```
