### ISSUE TITLE
pjax.js doesn't load inline <scripts> when clicking browser's back button

### ISSUE THREAD

**Issue by proov** [defunkt/jquery-pjax#469]
Hello,

I'm a webdesigner, not a developper. I tried to do my best with this wonderfull script but i'm not sure i did well. I did my personal portfolio website on wordpress and used pjax to load the div#main content.

i run all my scripts before `</body>`, jQuery first, Modernizr and then PJAX (i don't support non-HTML5 browsers).

here is what i do for running scripts :
```javascript
(function($){
	if ($.support.pjax) {

		// Pjax Params
		function initPjax(nextUrl){
			$.pjax({ 
				url: nextUrl, 
				container: '#main', 
				fragment: '#main',
				timeout:  10000
			});
		}

		// Pjax Init
		$(document).on('click', ".menu a, .logo a, .work-nav a, .footer-links a, a.pjax-link", function(e) {
			e.preventDefault();
			var nextUrl = $(this).attr('href');
			bod.addClass("pjax-loading");

			$pjax_container.velocity({ opacity: 0 }, {
				duration: 200,
				complete: function(){
					initPjax(nextUrl)
				}
			})
		});

		// Pjax Animation (In)
		$(document).on('pjax:end', function(e) {

			// Workaround to reload inline scripts in page loaded via popstate/pushstate (founded here)
			$(e.target).find('script').each(function() {
				$.globalEval(this.text || this.textContent || this.innerHTML || '');
			})
			$pjax_container.velocity({ opacity: 1 }, { duration: 200 })
		});

	}
})(jQuery);
```

everything works perfectly thanks to the workaround founded on this "forum" (before this, the inline scripts wasnt executed when pages loaded via popstate/pushstate.

So the BUG is, it's still doesn't work, when i clicking BACK button of the browser. Not NEXT. Very strange... When you try to load "Travaux" by clicking BACK button, Isotope.js is not loaded.. 

You can see here : http://proov.fr

If someone can help me, it would be nice :)

Thanks a lot :)

**Comment by mislav** [comment]
Inline scripts should be automatically executed by jQuery because pjax uses jQuery's `fn.html()` internally to replace the contents. You shouldn't need to do anything extra to gain this behavior, either on pjax navigation or on "Back" button.

What is the `lsotope.js` script and why do you expect this script to have been loaded?

**Comment by PofMagicfingers** [comment]
@mislav : If it works, it should not! I think jQuery's `fn.html()` use `innerHTML` internally and the HTML5 specs say this : 
> script elements inserted using innerHTML do not execute when they are inserted.
>
> Source : [Footnote of innerHTML paragraph in 2.5.2 Dynamic markup insertion in HTML](http://www.w3.org/TR/2008/WD-html5-20080610/dom.html#innerhtml0)

I had this issue myself, and found somewhere (maybe in some other issue of this repo) a workaround, here is my version of it :

Add this on a normal script tag or your js file :
```javascript
  $(function() {
    $(document).on("pjax:popstate", function() 
      $(document).one("pjax:end", function(event) {
        $(event.target).find("script[data-exec-on-popstate]").each(function() {
          $.globalEval(this.text || this.textContent || this.innerHTML || '');
        })
      });
    });
  });
````
And next time you use inline `<script>` tags needing to be executed when Back/Next button is pressed just add `data-exec-on-popstate` on the script tag : 
````html
    <script data-exec-on-popstate>
        alert("Hello, I'm seen every time the page load")
    </script>
    
    <script>
        alert("Hello ! I'm only seen the first time the page is loaded")
    </script>
````

**Comment by mislav** [comment]
@PofMagicfingers jQuery automatically does the equivalent of your code above: on `.html(content)`, it iterates over inline script tags and eval's them.

**Comment by PofMagicfingers** [comment]
@mislav : Yup, but it doesn't work when you pop state, because jQuery marked them as already executed : [See this line](https://github.com/jquery/jquery/blob/85ffc6d973865a031ded170934e0acfc2e97cb11/src/manipulation.js#L536)

**Comment by lustremedia** [comment]
+1

**Comment by mislav** [comment]
Thanks for the tip @PofMagicfingers! I wouldn't have figured that out by myself.

**Comment by PofMagicfingers** [comment]
Don't mention it ;-)

**Comment by lombo** [comment]
I'm still having this issue (though globalEval is being set as false) using jQuery 2.1.4 and the latest pjax

@mislav @PofMagicfingers as a side note, jQuery [is going to drop _data](https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/data.js#L14) and hide implementation details. So it is likely this will break in the future!

```javascript
//	Implementation Summary
//
//	1. Enforce API surface and semantic compatibility with 1.9.x branch
//	2. Improve the module's maintainability by reducing the storage
//		paths to a single mechanism.
//	3. Use the same single mechanism to support "private" and "user" data.
//	4. _Never_ expose "private" data to user code (TODO: Drop _data, _removeData)
//	5. Avoid exposing implementation details on user objects (eg. expando properties)
//	6. Provide a clear path for implementation upgrade to WeakMap in 2014
```
