### ISSUE TITLE
Javascript Replace fails

### ISSUE THREAD

**Issue by ricardopolo** [defunkt/jquery-pjax#470]
Hello.

I have some JavaScript that search text inside the pjax container and replaced it. Imagine search the keywood FirstName and replace it to John.
````js
$('#pjax-container').html($('#pjax-container').html().replace(/(FirstName)/ig, '<span>John</span>'))
````

it works in a normal Request. (If you press F5 it works)
But when the request is a Pjax rquest the script fails.

If I evaluate the execution using Chrome I see the script has been replaced
````js
$('#pjax-container').html($('#pjax-container').html().replace(/(<span>John</span>)/ig, '<span>John</span>'))
````

What Pjax does that changes my script?

**Comment by mislav** [comment]
You'll need to provide more info. Where do you put your script? How exactly does it fail? What is the error message?

**Comment by ricardopolo** [comment]
This is a invalid Issue. After some testing we found Pjax was no the culprid. Sorry.
