### ISSUE TITLE
Ignore first go back requeast.

### ISSUE THREAD

**Issue by ctf0** [defunkt/jquery-pjax#473]
lets say u have a search form ,so u enter what u want to search for and the plugin kickin > fetches data ,no prob at all.

now search once more and try to go back ,the first request will be ignored but will work from the second try.

i dont know if this is a bug or is it just related to my app.

**Comment by mislav** [comment]
Sounds like it might be related to your app. It's especially hard to know what's going on when you didn't provide any code nor explained what did you mean by "the first request will be ignored".

**Comment by ctf0** [comment]
i mean when u press the back button to go to the prev page ,the first time u press on the button it wont work but when u press it again the page will behave as expected ,

i dont know what code should i post ,its a simple search form that use pjax to load the new data.

**Comment by mislav** [comment]
Generally, when you're reporting a bug that you want someone to investigate, you have to help them reproduce it. So, ideally you would share some pjax setup code that's in your app. Also, what kind of server response do you get when submitting a form via pjax?

**Comment by ctf0** [comment]
i can search without any prob ,i can test with `pjax:send` & `pjax:complete` ,
as for the the request status
![ss](https://cloud.githubusercontent.com/assets/7388088/5793801/441a60ca-9f5a-11e4-84cc-2b969e44767a.jpg)
but oddly enough everything is working just fine.

**Comment by mislav** [comment]
So do you think there's a bug with our library here? If not, we can close
this issue.

**Comment by ctf0** [comment]
the bug is there but beyond the above i don't know what other data/reports u want me to submit to help git it fixed :(.

**Comment by mislav** [comment]
Are you worried about seeing that pjax request cancelled in the web inspector, but your site is otherwise working fine? A cancelled pjax request is nothing to be alarmed about; it simply means that another pjax navigation attempt was made (either by clicking a link, submitting a form or pressing Back) while there was already pjax in progress, so the earlier request got cancelled in favor of the later one.

**Comment by ctf0** [comment]
okey ,thanx.

**Comment by pph7** [comment]
On thing that might be the case here is that you have a double event binding on your back button so the event is called twice and the first call is being cancelled.

**Comment by ctf0** [comment]
@pph7 is there away to debug that second event ?

**Comment by mislav** [comment]
@ctf0 You could add listeners for `pjax:start` and `pjax:end` and have them log to the console. If you get double events a lot of times, then you know you might have double event bindings.

**Comment by ctf0** [comment]
fixeeeeeeeeeeeeeeeeeeeeeeed ,thanx @mislav ,the problem was with
```
$('#sub').click(function(e) {
	if (!$('#search').val()) {
		e.preventDefault();
	} else {
		$('#s-form').submit();
	}
});
// and
$('#s-form').submit(function(event) {
	$.pjax.submit(event, '#result');
});
```
so now the button was submitting the form twice ,
one by pjax and one by the 2nd event ,and removing that fixed it ,thanx again.

**Comment by pph7** [comment]
Do you give me some credits too? ;)

**Comment by ctf0** [comment]
oh i forgot @pph7 :tophat: (i tried to find the YOU ROCK icon but dont know where ppl get thier hands on such gems)

**Comment by pph7** [comment]
thx ;)

**Comment by mislav** [comment]
you rock icon = :boom: :metal: :bow:

**Comment by ctf0** [comment]
@mislav u r my hero ,btw is there away to make the code above work by any mean ?

**Comment by mislav** [comment]
I'm not sure what you're tring to do with the code above, so I can't help you much. I'm assuming that you want to allow a form being submitted by pjax, but prevent the form submit if the search field is empty. In that case:

```js
// This assumes that "#sub" is a regular `<input type=submit>` and therefore it will
// trigger form submit on click without any special "click" handler.
// This also assumes that "#search" is a text field within the form.

// Handle all submit events of "#s-form":
$(document).on('submit', '#s-form', function(event) {
  var form = this, searchField = form.querySelector('#search')
  if (searchField.value) {
    $.pjax.submit(event, '#result');
  } else {
    // "#search" value is empty so abort the form submit:
    return false    
  }
});
```

**Comment by ctf0** [comment]
@mislav appreciated :+1:
