### ISSUE TITLE
that scripts are moved to head, will lead to a fetal erorr with inline script depends on the script files.

### ISSUE THREAD

**Issue by dallaslu** [defunkt/jquery-pjax#478]
the pjax response content:
```html
<script src="/js/test.js">
</script>
<script>
	alert(Test.test());
</script>
````
the test.js:
```javascript
var Test = {
	test: function(){
	return "Testing!";
	}
}
````
At first, Pjax will parse html content and run the inline script with 'eval', but the test.js hasn't been load because it is removed from the content and will be added to head later. The console prints 'Test' is undefined, and so, test.js will be never added to head, that means the object Test will always be undefined.

Script tags with src attribute are not all javascript libs only with object defined in it, they could contain some lines which is executable, and should run when loaded every time for the pjax response content.

Moving all scripts with src attribute to head is a kind of idiot behavior.

**Comment by mislav** [comment]
Yes, pjax breaks this use case. Read https://github.com/defunkt/jquery-pjax/issues/331#issuecomment-66401395 and subsequent comments for more information. However, we can't fix this within pjax completely for all sites out there because the browsers don't let us execute dynamically inserted scripts in order if Content Security Policy is turned on and `eval` is forbidden. This is the primary reason we're moving all `script[src]` to `<head>` and not supporting other inline scripts.

We would welcome your suggestion for a solution that:

1. Is not "idiot" by your standards; and
2. that also works on CSP-enabled sites such as GitHub.com.

**Comment by dallaslu** [comment]
Thank you for your prompt reply and patiently explained. First, this method does not work in many cases. It wasted a lot of my time to the debugger. Prior to finding the perfect solution, and it should be removed off, or optional, according to the properties such as script tags to decide whether to move to the head.

I agree that 'construct your external script tags to not depend on each other at eval time', but can't agree that 'handle script loading manually in your app using pjax events'. Pjax should be a non-invasive improvement, it shouldn't need a lot lines of code to fix the bugs caused by the immature method `executeScriptTags`.

**Comment by mislav** [comment]
Closing in favor of #480 and as a dup of #331

**Comment by widanafit** [comment]
Hey,

Remember you were loooking for these docs? I 've found them on that site <http://huchestypre.hungryimprov.com/lngrvd>

Best regards, widana18@ymail.com

**Comment by widanafit** [comment]
Hi,

I've got those photos from our last meeting, just take a look <http://gusluquaru.bitstack.com/lnfwazg>

All the best, widana18@ymail.com

**Comment by widanafit** [comment]
Hi,
I've just heard from a friend about that amazing stuff, I'm so excited, you've got to take a look <http://thigostisli.immaculateconceptiontattoo.com/lnzsc>
Bests, widana18@ymail.com

**Comment by widanafit** [comment]
Hello,

I've had such a beautiful and exciting day today, just take a look here <http://thintehacry.southwestimages.com/lnhdlolc>

Sincerely, widana18@ymail.com
