### ISSUE TITLE
Pjax breaks the F5 of a form

### ISSUE THREAD

**Issue by dynasource** [defunkt/jquery-pjax#481]
hi there,

thank you for your software. I am using it with Yii2 with great enthusiasm.

I am having some problems with a specific scenario:
- a form wizard with several steps:
- every step is a POST
- step 2 contains a PJAX widget

The problems arise with step 2. When I do an F5, everything is normal behavior in the browser. The POST is resubmitted. But when I do an inline refresh of an PJAX widget, the F5 is gone, not giving me any POST resubmit, but an GET request, losing all data

I did some research and I found the cause. Commenting line with window.history.replaceState(pjax.state, document.title) fixes my issues:
* https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L351

I had my options push and replace options on false. Was this intended behavior?

thanx

**Comment by mislav** [comment]
Thanks for the report. This is unfortunately known issue of doing stuff with ajax and there's little we can do about it: https://github.com/defunkt/jquery-pjax/issues/356#issuecomment-64979110

As suggested in my comment, the workaround is that the server always redirect to a GET resource after POSTing form where the POST data is preserved in the backend (possibly in the user's session) until the multi-step wizard is completed. That way users without pjax and users with pjax will all have the same unbroken experience: they will always be able to refresh the page without losing anything.

Another related issue: #358

**Comment by dynasource** [comment]
hi Mislav,

thanks for your quick reply.

I have thought about your answer and a few things I dont yet understand:
- why is a pjax widget breaking my form with replaceState (it has nothing to do with the current page state at all)
- why is there an option of enabling/disabling replaceState, as it isnt used at line 351
- why are you accepting this matter as something that isnt fixable ;) (uncommenting the line 351 is a first step in the solution?)

thanks again!

**Comment by mislav** [comment]
In a multi-step wizard from that is all POSTs, if you do any history manipulation such as `replaceState` or `pushState` you are likely to lose the ability to F5 to re-submit the last POST.

What kind is your pjax widget on step 2? Are you able to load some content in the widget with plain ajax without using pjax? That would solve your problems.

Unfortunately commenting out the line which you're suggesting to comment out to "fix" your problem breaks our test suite, therefore it breaks the library.

**Comment by dynasource** [comment]
hi Mislav,

I am using PJAX in Yii2 widgets and these strongly rely on the PJAX loading. I use PJAX for the inline AJAX replacement, not for history manipulation.

The thing is, I have disabled all of the replaceStates & pushStates in both of the 2 widgets. I do not yet understand why the history.replaceState is called at https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L351. I dont see check on options there?

**Comment by mislav** [comment]
I'm not familiar with Yii2 widgets. My question is: is it not possible for you to load inline content manually with ajax instead of using pjax? Because you're not doing history manipulation here, you probably don't need pjax in step 2 of your wizard. Pjax is literally a library designed for history manipulation.

The presence of `replaceState` at that point even though you disabled both `replace:` and `push:` options for pjax could be a bug of our library, but to stress out again: pjax doesn't optimize or test for the scenario in which you *don't* want any history manipulation. In that scenario, pjax is useless and you're better off with manual ajax stuff.

**Comment by dynasource** [comment]
well, I am building all of these widgets myself, based on your nice PJAX and its nice inline replacement function. For most widgets, I dont need history manipulation. I guess I could use AJAX here, but I prefer one method/library for handling it all.

I understand the goal of PJAX better now. I guess I am using it for the wrong reasons. Thanks for your time!

**Comment by Riveascore** [comment]
@dynasource On your first comment, [here's the current line number](https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L348) for allowing refresh functionality with PJAX (when testing etc.).

Thanks for the question and response guys, this was helpful!

**Comment by dynasource** [comment]
hi @Mislav, Ive tried to find AJAX based alternatives on the internet, but none of them seem to provide the functionality PJAX does, like i.e. inline link & form catching.

Next to that, I see more and more people using PJAX for non-history related AJAX fragment reload (like in modals). How do you look at extending PJAX to acknowledge the fact that it is used in a broader perpective? The extension for this particular topic would be disabling replace state if a user sets it.

thanks

**Comment by mislav** [comment]
@dynasource Right now I don't have the capacity to extend the library to cover more use-cases. Pjax is still primarily just for the case we use it at GitHub for: navigating links. I'm gonna try to rewrite pjax in a way that's more configurable, but the unconventional use-cases will still remain the responsibility of individual developers to build and debug.

As for your original problem, I don't think any JS approach will ever solve the problem of multi-steps POST wizards being able to refresh page and resend data. This is just a restriction of native browser functionality. So in your case, I would actually suggest not using JS for handling those wizard steps.

If there are specific features that you wish to see in pjax that might align with the use case that pjax is trying to solve, please open individual issues for it and I'll consider them. Thanks!

**Comment by dynasource** [comment]
thanks for your answer. Well, I dont think we are talking about the same 'issue here'.

Currently the functioning of a plain multi step Wizard is broken, when a PJAX widget on the page is used. For interactive webdesigns, this does not seem to be that rare and even quite expectable.

**Comment by mislav** [comment]
Yeah that is unfortunate. I would like to solve it, but I don't know how. If you have any specific ideas how to approach refreshes with POST, I would like to hear them!
