### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by flashtopia** [defunkt/jquery-pjax#483]
In GIthub Search results, is the paging done using Jquery-Pjax? I noticed the urls are chaning like HMTL push state

**Comment by mislav** [comment]
Yes, a lot of navigation on GitHub is done using this jquery-pjax library. We've set it up so that any link that has a `data-pjax` attribute or is contained in an element that has the `data-pjax` attribute is pjax-enabled by default.

Does that answer your question?

**Comment by flashtopia** [comment]
yes.  thanks.
