### ISSUE TITLE
Pjax and Response JSON?

### ISSUE THREAD

**Issue by Yarisrespect** [defunkt/jquery-pjax#485]
Pjax.options.dataType NOT using!

**Comment by mislav** [comment]
Yes, pjax doesn't support JSON responses. Pjax is a library that fetches a partial HTML for the next page from the server and replaces the current content with the new HTML. Pjax as a library doesn't make sense when the server response is something other than HTML, like JSON.

See https://github.com/defunkt/jquery-pjax/issues/435#issuecomment-55927932
