### ISSUE TITLE
Javascript on load different in each page

### ISSUE THREAD

**Issue by ricardopolo** [defunkt/jquery-pjax#487]
Hello.

What is the best way to manage call a script on page load?

````
$(document).ready(function() {
    // page load stuff
});
````
Works for first load

````
$(document).on('ready pjax:success', function() {
    // will fire on initial page load, and subsequent PJAX page loads
});
````
Works for Pjax loads... but not when the user use back button.

Also `'ready pjax:success'` starts in every page. 
What can I do if the initialization code is different for each page? And how can we force the initialize even when the users use the back and forward button of his browser?

**Comment by mislav** [comment]
You probably want this:

```js
$(document).on('ready pjax:end', ...)
```

The `pjax:end` event fires on pjax navigation *and* back/forward buttons all the same. For more information, refer to [Events section of our documentation](https://github.com/defunkt/jquery-pjax#events). The differences between lifecycle events during pjax navigation vs. back/forward buttons should be clear there.

**Comment by ricardopolo** [comment]
@mislav while using `end` event I see it is fired in every request end (using ajax or back/forward).

Is it possible to have an event that is fired only when one page loads?  Not when any page load?

**Comment by mislav** [comment]
The event will always fire regardless of which page. To do conditional initialization of specific pages, you can do one of the following

* Check the current page's URL and perform initialization specific to that URL; or
* Check for some DOM elements on the current page and perform some initialization only if those elements are present.

But this is really your application's logic and has nothing to do with this library. Pjax doesn't know what specific JS things you want to run on specific pages. You'll have to do it yourself.

Alternatively, you could have inline `<script>` tags in pjax responses but I would advise against that. It won't work with Content Security Policy when enabled across the site, and currently there's a pjax bug where script tags only get executed on first load of a page with pjax but not on back/forward navigation.

**Comment by ricardopolo** [comment]
@mislav thank you. Now I undesrtand in line scripts does not run in back/forward navigation... So would you recommend to change all scripts to the Main HTML or wait to the fix?

**Comment by mislav** [comment]
My general recommendation for all sites (regardless of pjax) is that they never use inline script tags. But because of sites that still do, I will try to patch this bug for the next release.

**Comment by ricardopolo** [comment]
@mislav So i wont use script tags, Thank you!

**Comment by dynasource** [comment]
> My general recommendation for all sites (regardless of pjax) is that they never use inline script tags

How would you advise to work with dynamic JS variables?

**Comment by mislav** [comment]
> How would you advise to work with dynamic JS variables?

As usual: you assign to them like `var foo = 1`

Then when you need you read them like `foo + 2`.

As for your other concerns, possibly related to pjax, I'm afraid you'll have to be more specific with your questions.
