### ISSUE TITLE
jquery-pjax and browserify?

### ISSUE THREAD

**Issue by kirkbushell** [defunkt/jquery-pjax#488]
I had this working outside of a modular environment, but now inside browserify this just doesn't appear to be making the correct bindings. I'm not sure why - all my code is running inside a domready callback, so the HTML is ready and waiting, and when I do checks on the elements I need to make pjax work, they all return the appropriate dom elements.

Has anyone had any luck getting this working in a modular fashion and/or know of any gotchas that prevent it from working?

**Comment by mislav** [comment]
What is the actual issue you're having?

**Comment by kirkbushell** [comment]
It's okay, figured it out in the end. The "document" object wasn't available so wasn't able to bind inside a browserify module. had to bind to "body" as the basis for the setup.
