### ISSUE TITLE
Cache in Internet Explorer

### ISSUE THREAD

**Issue by ricardopolo** [defunkt/jquery-pjax#490]
I have a webpage using ajax. The page contains a form that edits a text field.

When using Internet Explorer for save a new value in the form, the next time I see visit the form it shows the old value due the browser cache.

So I put this line the website in JS of the webpage
`$.ajaxSetup({ cache: false });`

Now in IE it works. No values are cached.

But in Chrome I see a new ID in all urls.
![capture](https://cloud.githubusercontent.com/assets/1263856/6274604/a85bdb68-b846-11e4-9a7c-10d31843e967.PNG)

Any idea?

**Comment by ricardopolo** [comment]
@defunkt any idea about this ID in URL of Chrome?

**Comment by ricardopolo** [comment]
@mislav I Understand this PR (#489) removes the URL Do we need still to set `cache: false` for IE?

**Comment by ricardopolo** [comment]
@mislav would you bump the new bower release?

**Comment by mislav** [comment]
You referenced the wrong PR, but this one https://github.com/defunkt/jquery-pjax/pull/496 fixes your problem.

You can fetch the latest `jquery.pjax.js` version directly from master. Otherwise, you'll have to wait for me to make a new release and publish to Bower. It might be a day or two.

**Comment by mislav** [comment]
And thanks for reporting this issue! I wasn't aware that the `_` param could appear in URLs.

**Comment by ricardopolo** [comment]
@mislav thanks for fixing it. I just tested the latest version from master and now we dont have the strange URL id. We stil need cache false for correct IE working.
