### ISSUE TITLE
PJAX fails to make request when popping to root url with hash

### ISSUE THREAD

**Issue by thelucid** [defunkt/jquery-pjax#495]
I you are currently on `localhost:1234/path` and were previously on `localhost:1234/#somehash`, when you press the back button, the PJAX doesn't fire meaning you are left viewing the wrong page.

**Comment by thelucid** [comment]
The tab implementation I am using on the root path uses `history.pushState(null, null, href);` in order to change the hash without causing the page to scroll, not sure if this would be interfering.

**Comment by mislav** [comment]
Pjax doesn't work perfectly when you use `pushState` manually on the page. The `null` state that you push onto the history stack in your example above confuses pjax, and when it encounters it, it simply does nothing. That's what you experienced when you said "PJAX doesn't fire".

It might help you to do `history.pushState($.pjax.state, null, href)` instead, but I'm not sure if it will be a perfect workaround for you. My suggestion would be to use `history.replaceState($.pjax.state, null, href)` when switching tabs, but then you won't be able to use the back button to go to previous tab.

In any case, right now this is not a bug with pjax, but I'm aware that pjax doesn't play well with other pushstate usage on the same page. Ideas how to improve this going forward welcome.

**Comment by mislav** [comment]
Also see #381

**Comment by proov** [comment]
Hey Thanks @mislav !! your workaround works perfectly for me! i tried ```history.replaceState($.pjax.state, null, href)``` and i can go to the previous page and keeping the hash in url. Many thanks :)
