### ISSUE TITLE
ReferenceError: stripPjaxParam is not defined

### ISSUE THREAD

**Issue by yoopy** [defunkt/jquery-pjax#497]
After today update i have error "ReferenceError: stripPjaxParam is not defined"

**Comment by mislav** [comment]
The `stripPjaxParam` function was removed in the latest release and there is no code within pjax that calls it anymore. I don't see how you could have got this exception. Can you search for the function name in your own application and report back?

**Comment by yoopy** [comment]
Sorry for the false alarm. pjax used in yii2 framework, and developers already updated extension
