### ISSUE TITLE
Recent commit causes issue with external and inline scripts

### ISSUE THREAD

**Issue by tremby** [defunkt/jquery-pjax#502]
Commit https://github.com/defunkt/jquery-pjax/commit/00191366fae68a188286ebb65ec342cb3f6ff37b introduces an issue on a site I'm working on.

I'm using the PHP debug bar, which injects some code at the end of the body tag of the page. The code includes an external script (jquery, in case you didn't already have it loaded, and whatever code it needs to run) and then an inline one (`jQuery.noConflict(true)`).

When pjax does its thing, the external one is skipped but the inline one runs. This has the effect of knocking out _my_ instance of jquery, and then my page breaks.

This is most likely PHP debug bar's bug (I imagine noConflict could be included in the external script, and then we wouldn't have this problem), but I wanted to flag it in case it's a case you hadn't considered.

**Comment by mislav** [comment]
> When pjax does its thing, the external one is skipped but the inline one runs.

What exactly is the navigation when "pjax does its thing"? Do you click a link? Do you press browser back button?

**Comment by tremby** [comment]
Yes, sorry, that wasn't clear. When clicking through to a different page via pjax the code at https://github.com/defunkt/jquery-pjax/commit/00191366fae68a188286ebb65ec342cb3f6ff37b#diff-256b2e7d3ffe31142c00fa086e15d3a6R551 runs. This (as far as I can tell) marks the inline scripts as being runnable again. Then when the user hits "back" in the browser those scripts run again, and the one mentioned above has the `noConflict` call in it, which wipes out my `$` and `jQuery` references since the external jquery hasn't been loaded again.

**Comment by mislav** [comment]
Do you expect external jQuery to be reloaded every time? Why would you want that?

Can't you move jQuery and `noConflict` call to `<head>` of the whole site so it only gets loaded once and not per every pjax page?

**Comment by tremby** [comment]
> Do you expect external jQuery to be reloaded every time? Why would you want that?

No, I never said I wanted that. Nothing has changed with how external scripts are handled. It is pjax's handling of inline scripts which has changed, and which is causing issues for me.

The purpose of this ticket is to point out that a pair of external and inline scripts might be used in this sort of way, in case it had not been considered. Perhaps you would want to reconsider rerunning one kind but not the other. And perhaps not. It does seem odd to me that they would be handled differently.

> Can't you move jQuery and `noConflict` call to `<head>` of the whole site so it only gets loaded once and not per every pjax page?

No. As explained above, these scripts are injected by a debugging tool. And I also acknowledged that it is likely best fixed there.

**Comment by mislav** [comment]
> The purpose of this ticket is to point out that a pair of external and inline scripts might be used in this sort of way, in case it had not been considered. Perhaps you would want to reconsider rerunning one kind but not the other.

I see. Thanks for reporting this.

I'll switch to unmarking `<script src>` as run as well. But, for them to run synchronously and in order, we'll first have to solve https://github.com/defunkt/jquery-pjax/issues/331#issuecomment-66403339

Until then, pjax doesn't work well with page contents that has a mix of external `<script src>` and inline `<script>` tags.

**Comment by mislav** [comment]
Closing in favor of the above referenced issue (referenced scripts executing async).
