### ISSUE TITLE
Shouldn't render full page on 4xx

### ISSUE THREAD

**Issue by kirkbushell** [defunkt/jquery-pjax#509]
A 4xx status code is usually a CLIENT issue, not a SERVER issue. As such, a full page refresh shouldn't be warranted. Think validation problems, which should return with a 400 or 422. These would usually re-render the form.

Also, some 500s should still allow jquery-pjax to handle it normally, and these should be configurable. If it is, please let me know :)

**Comment by mislav** [comment]
To be clear: you want a hook so you can choose whether you will handle the error yourself or let the page refresh?

[You can listen to the `pjax:error` event](https://github.com/defunkt/jquery-pjax#events) and cancel it if you want to avoid the page refresh so you can implement your own fallback. Let us know how it goes.

**Comment by kirkbushell** [comment]
Oh nice. That's a great idea - thank you @mislav :)
