### ISSUE TITLE
Handling file uploads with pjax

### ISSUE THREAD

**Issue by imkarthikk** [defunkt/jquery-pjax#515]
I recently moved to using PJAX from my own solution. While I'm super happy about the way it work, the upload functionality in my platform is now broken. 

Here's how my app works:
- I'm handling multiple file uploads with [jQuery File Upload](https://github.com/blueimp/jQuery-File-Upload)
- My backend is Rails + [Carrierwave](https://github.com/carrierwaveuploader/carrierwave)
- Earlier, I was able to navigate between pages, even when the file is being uploaded
- Since PJAX is loading a new DOM on every request, the `$(window).on('beforeunload', function() { });` is being called, which is preventing the user to upload the files

Here's what I would like to achieve:
- The user should be able to move around the platform even when the file upload is in progress (It used to work earlier with my own hacked solution)

I'm using `pjax:end` to load the JS functions that I want:

``` javascript
$(document).on('pjax:end', function(event) {
    console.log('Force Load');
    function1();
    function2();
});
```

And here's the jQuery File Upload's JS:

``` javascript
// Code for managing the entire uploads and progress bars - QC - OK
    var count = 0;
    var removeUploadStatusBoxOnCompletion = function() {
        if (count == 0) {
            $('.upload').hide();
            $('.external-drop-indicator').hide();
            $('#inline-upload-status').hide();
            $('.upload-status-box').hide();
        }
    };
    // Initialize the jQuery File Upload plugin - QC - OK
    $('#fileupload').fileupload({
        dataType: "script",
        sequentialUploads: true,
        // This function is called when a file is added to the queue;
        // either via the browse button, or via drag/drop:
        add: function(e, data) {
            data.context = $(tmpl("template-upload", data.files[
                    0]))
            data.context.addClass('working');
            //$('.upload-status-box').addClass('working');
            $('#Upload-Bar').append(data.context);
            $('.upload-status-box').show();
            // Listen for clicks on the cancel button
            data.context.find('span.cancel-upload').click(
                function() {
                    jqXHR.abort();
                    data.context.fadeOut(function() {
                        data.context.remove();
                    });
                    count = count - 1;
                    removeUploadStatusBoxOnCompletion();
                });
            var jqXHR = data.submit();
            count = count + 1;
        },
        progress: function(e, data) {
            if (data.context) {
                $('.upload-status-box').show();
                progress = parseInt((data.loaded / data.total) *
                    100);
                var uploadMeta = parseInt(data.loaded / 1000000) +
                    "/" + parseInt(data.total / 1000000) +
                    " MB - " + progress + "%";
                data.context.find('.progress-bar').css('width',
                    progress + '%');
                data.context.find('.status').text(uploadMeta);
            }
        },
        done: function(e, data) {
            console.log(
                'Your files have been uploaded successfully!'
            );
            // alert('Your files have been uploaded successfully! Depending on the file size, you might have to wait for a while before performing any actions.');
            count = count - 1;
            data.context.removeClass('working');
            data.context.find('button.cancel-upload').hide();
            removeUploadStatusBoxOnCompletion();
        }
    });
    // Alert user when he or she is moving away from the page - QC - OK
    $(window).on('beforeunload', function() {
        if ($('div.working').length != 0) {
            return 'Your files are still being uploaded. Moving away from this page might cancel the uploads!';
        }
    });
```

It would be great if someone could help me out with this! Thanks in advance.

**Comment by mislav** [comment]
> Earlier, I was able to navigate between pages, even when the file is being uploaded

What solution did you use to navigate between pages without the page actually refreshing (and canceling the upload)?

> Since PJAX is loading a new DOM on every request, the `$(window).on('beforeunload', function() { })` is being called, which is preventing the user to upload the files

That sounds strange. Even though pjax is loading new partial page content to insert into the DOM, it never actually refreshes the page (that's whe whole point of it) so during regular pjax navigation, `onbeforeunload` will never get called because the page will never actually refresh.

However, in some cases pjax will hard-reload the page— such as when it receives a full `<html>...` response from the server but it's not configured to extract any particular `fragment: "#selector"` from it, or when it receives an empty response from the server.

Thank you for opening an issue in such great detail, but in order to understand your problem better, I'll need you to elaborate a bit more on exactly what happens during pjax navigation on your site and how that messes up uploads. Thanks

**Comment by imkarthikk** [comment]
Hey @mislav, Thanks much for replying. 

> What solution did you use to navigate between pages without the page actually refreshing (and canceling the upload)?

I used to have `:remote => true` for which the controller replies back with a JS response that replaces a div with a partial. This way, the DOM used to load, but then, I was loading the functions that I need inside a ajaxComplete() method. I realized that this was wrong. 

> However, in some cases pjax will hard-reload the page— such as when it receives a full <html>... response from the server but it's not configured to extract any particular fragment: "#selector" from it, or when it receives an empty response from the server.

So does it mean that if I add the `:remote => true` back to the links, and respond as a HTML from the Controller, PJAX should work fine? Or do I return a JS?

I will be happy to provide more information if required. :+1:

**Comment by mislav** [comment]
You definitely don't want to use `:remote => true` together with pjax at the same time. They are doing different things and shouldn't be used in combination.

> I used to have `:remote => true` for which the controller replies back with a JS response that replaces a div with a partial.

That sounds alright, but that means that the browser URL never updated and that you never enabled browser Back/Forward navigation in history. If you want those things, then pjax is definitely the way to go. But, as you guessed, you will have to stop serving JS as response to pjax requests and start serving HTML fragments. You only need to render the HTML partial that is to be inserted within the element that is the "pjax container", e.g. element with ID `#main`.

Example controller action:

```rb
def index
  respond_to do |format|
    format.html do
      render :layout => !pjax?
    end
  end
end

def pjax?
  request.headers["X-PJAX"]
end
```

Now the `index` action will serve layout-less HTML for all pjax requests.

Alternatively, if you don't want to change how your backend reponds to pjax request and have it continue rendering full HTML (with layout) for all requests, then you can configure pjax on the front-end to just extract one fragment of that HTML that it receives. Configure it like so:

```js
$(document).pjax('a', '#main', { fragment: "#main" })
```

Now pjax will expect to find the `#main` element in each server response that it receives, and will extract its contents and insert into the `#main` container currently in the DOM.

**Comment by imkarthikk** [comment]
Thanks for the detailed answer @mislav . I'll quickly check these with the code and get back to you. :)

**Comment by imkarthikk** [comment]
@mislav : Really appreciate your help. Your answer above helped me fix some stuff in making PJAX work with Rails. But I now have a new issue. The History PushState ID is being appended to the URL like this: `http://localhost:3000/myfolders/1?_=1428680562715`

And any form that's being submitted also prints the parameters in the URL field and then submits it, which clearly exposes the data that's being sent. Another issue is that, whenever a user refreshes the page with `cmd+r` or hard refreshes it, the DOM does not load. I suspect that it might be because of the parameters that are appended to the URL. 

To give you some more information. Here's how my JS looks like:

```javascript
# app/assets/javascript/application.js
$(document).pjax('a[data-pjax]', '[data-pjax-container]', { fragment: '[data-pjax-container]' });
```

And here's how I trigger PJAX to replace the contents of `<div data-pjax-container>`:

```ruby
# index.html.erb
<%= link_to myfolder.realname, myfolder, :data => {pjax: ''} %>
```

As I mentioned earlier, I'm trying to replace the contents of `<div data-pjax-container>` alone, and that part works perfectly. But the issue is, I have the file upload form outside of the `pjax-container`. While everything should have worked just fine in this case, the `beforeunload` is being triggered whenever I navigate using PJAX:

```javascript``javascript
    $(window).on('beforeunload', function() {
        if ($('div.working').length != 0) {
            return 'Your files are still being uploaded. Moving away from this page might cancel the uploads!';
        }
    });
`````

Its been a week already, and we just have two days to production. This is the only thing that's scaring me out like crazy. Its been a week already, and we just have two days to production. This is the only thing that's scaring me out like crazy.
