### ISSUE TITLE
Cancel does not work

### ISSUE THREAD

**Issue by Arwany** [defunkt/jquery-pjax#519]
Hi,

I am trying to cancel the request if some conditions are not met, but it seems that it is not preventing the action, any ideas?

I wrote the following:

```javascript


$(document).pjax('a', 'container', {maxCacheLength: 0, replace: true, scrollTo: 0});

$(document).on('pjax:click', function () {
        //console.log('Saving: ' + saving + ', Loading: ' + loading);
        if ( !condition ) {
            console.log('Stopping the loading...');
            event.preventDefault();
        }
});
```

The code above seems to continue to load the clicked link and put its content in the container.

**Comment by Arwany** [comment]
Sorry, just figured it out after reading the #428 by making simple return false; like this:

```javascript
$(document).on('pjax:click', function () {
        //console.log('Saving: ' + saving + ', Loading: ' + loading);
        if ( !condition ) {
            console.log('Stopping the loading...');
            return false;
        }
});
```

Thanks for this well implemented plugin.

**Comment by mislav** [comment]
`event.preventDefault()` should have worked as well, since we check `event.isDefaultPrevented()` later to see if the event was cancelled. In jQuery terms, `return false` is simply `preventDefault() + stopPropagation()`

**Comment by Arwany** [comment]
@mislav  Thanks for your time to answer, but it really did not work with me.

I am using the latest jQuery version (2.1.3) and using few small libraries like select2 and co... 

I have tried preventDefault() + stopPropagation() but it did not work for me as well.
