### ISSUE TITLE
Multiple triggers?

### ISSUE THREAD

**Issue by janhartmann** [defunkt/jquery-pjax#521]
First of all, great plugin - I got up and running pretty quick.

I have a search form which has a lot of criterias available. Once they are changed, a callback is fired which triggers `pjax` with this initializer:

```js
$.pjax({
	url: self.settings.searchResultUrl + "?" + $.param(data.contributors, true), // /search/?searchCriteria=1&searchCriteria=2
	container: self.settings.searchResult, // #search-result
	timeout: 5000,
	fragment: self.settings.searchResult // #search-result
});
```

This works good. Now, inside `#search-result` I have a pagination control (a bunch of links) to page the results coming back. How do I attach a handler to invoke `pjax` on those links?

As a side question, how can I restore my form on `popstate`?

**Comment by mislav** [comment]
> I have a search form which has a lot of criterias available. Once they are changed, a callback is fired which triggers pjax with this initializer:

Is there any option that you could just hook into the native "submit" event and have the form submitted automatically over pjax on supported browsers? The code would be:

```js
$(document).on('submit', '#search-form', function(event) {
  $.pjax.submit(event, '#search-result', {
    fragment: '#search-result',
    timeout: 5000
  })
})
```

That assumes that without pjax (or even JS, for that matter), the form submits normally, but in case pjax is available, it will take over and the form will be sumitted over XHR.

> Now, inside #search-result I have a pagination control (a bunch of links) to page the results coming back. How do I attach a handler to invoke pjax on those links?

Same as you attach pjax to any links. Please refer to README:

```js
$(document).pjax('#search-result .pagination a', '#search-result', options)
```

> As a side question, how can I restore my form on popstate?

What do you mean? In which way do you need to restore the form?

**Comment by janhartmann** [comment]
Great, I figurered this out from your response. Thanks :-)
