### ISSUE TITLE
Table rows and cells not rendered on pjax.reload()

### ISSUE THREAD

**Issue by slickorange** [defunkt/jquery-pjax#525]
I am using pjax.reload() to reload a container that contains a table. After the reload the table data is reloaded but the <thead>, <tbody>, <tr> and <td> tags are not rendered, so it ends up being a single paragraph of text. (Some of the table cells contain <span> tags - these are correctly rendered.) The <table> tag is rendered.
If I refresh the page the table is displayed correctly again.

Any ideas?

**Comment by slickorange** [comment]
I had an HTML error in my table: My opening table tag was <table class="table"/> (Stupid I know!) But since it rendered correctly on a normal page load I thought there was some kind of issue with PJAX.

**Comment by staabm** [comment]
Do you have separate view files for initial load and pjax load? this is something you should not have... best case is that it either works everywhere or nowhere (so both paths use the same views and differ only in very subtle ways)

**Comment by slickorange** [comment]
No I have the same view files. But it was just a stupid mistake on my side with having the closing tag in inside my opening table tag. It rendered fine on initial load. But when passed through as ajax request `<table class="table" />` got converted to `<table class="table"><table>`.
