### ISSUE TITLE
One container - two different actions

### ISSUE THREAD

**Issue by szewciu** [defunkt/jquery-pjax#527]
I have following issue: I need to use exactly one pjax container for two different actions.

To be exact, one of them is used for reloading gridview after form submitted. The second one is required to fill in form with data of model user'd like to edit. Even though in the first case script works correctly, the second one causes filling in right form and also replaces gridview to form.

Any suggestions how to solve this problem?

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
