### ISSUE TITLE
Abort request

### ISSUE THREAD

**Issue by vov4ik08** [defunkt/jquery-pjax#529]
Hello. I tried call pjax from backbone as         $.pjax({url: '/search?' ,container: '#content', timeout: 600000}), ajax request was cancelled, error in jquery on the line: 
f.send(a.hasContent && a.data || null)
Please help.

**Comment by vov4ik08** [comment]
if set parameter async: false the problem disappears.
but I think it is not the best solution

**Comment by mislav** [comment]
You're right, you shouldn't use `asnyc: false`. But I don't know where your problem might lie. It's something else in the application that's canceling the request. Without any extra info or steps to reproduce, I'm afraid I can't help you.

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
