### ISSUE TITLE
window.fetch integration

### ISSUE THREAD

**Issue by staabm** [defunkt/jquery-pjax#530]
Do you have any plans to integrate `pjax` with `window.fetch` instead of `jquery.ajax`?

I am pretty sure you already considered if this would be something worth doing for github.com :-).

**Comment by mislav** [comment]
Yes, see [github/pjax](https://github.com/github/pjax/blob/49180d8c4333d7659c48fed05cd2571e9d2107ce/src/pjax.coffee#L2)
