### ISSUE TITLE
No callbacks between replacing content and scrolling to fragment identified element

### ISSUE THREAD

**Issue by jievans** [defunkt/jquery-pjax#536]
There are no events fired between when PJAX replaces content and scrolls to fragment identified elements. 
### General problem

There's no opportunity to manipulate replacement content before PJAX does its scrolling work. This means if you insert a fragment identified element based on PJAX replacement content, PJAX will not scroll to it. 
### Specific example for React UJS

If using React UJS, one solution is to mount your React components once the `complete` or `success` events are fired. However, if an element corresponding to a fragment identifier is rendered by these mounted components, PJAX will not scroll to it, since the scrolling is done before any events are fired. Since there are no events fired between when PJAX replaces content and scrolls, there's no opportunity to insert the fragment identified element and take advantage of PJAX's scrolling.

**Comment by mislav** [comment]
I understand. Because your use case is so specific, maybe it makes sense to perform scrolling manually after you've inserted the content that you need?

**Comment by Linda6312** [comment]
??'

2015-06-11 2:33 GMT-05:00 Mislav Marohnić <notifications@github.com>:
