### ISSUE TITLE
$.support.pjax vs Modernizr.history

### ISSUE THREAD

**Issue by szegheo** [defunkt/jquery-pjax#538]
Not really a bug report, just an observation.
Pjax and Modernizr detects history support for problematic browsers versions slightly different:

https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L911
https://github.com/Modernizr/Modernizr/blob/master/feature-detects/history.js

Who is right?

**Comment by mislav** [comment]
Thanks for letting us know. I don't know who is right, but pjax's detection works fine for our purpose.
