### ISSUE TITLE
(bug) pjax submit not working (old browser)

### ISSUE THREAD

**Issue by paveleremin** [defunkt/jquery-pjax#539]
I have Nokia C5, and pjax not work at this device.

User Agent:
Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaC5-03/23.0.015; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.33 Mobile Safari/533.4

Difficult to say why because  window.FormData is exists
The problem is: post data not sending to the server (empty $_POST)
Maybe somebody know this issue?

The error that I had: [object Event], unfortunately this all information about error

**Comment by mislav** [comment]
Thanks for the report, but sorry, we don't support Symbian browser. If you could try to debug this issue and send a pull request to fix it, that would be great, but otherwise you will have to handle form submits yourself somehow.

**Comment by raphaelm22** [comment]
hi @paveleremin
I have the same problem in IE.
I used the implementation steps to resolve


```
$(document).on("submit", "form", function (event) {

	if (this.method.toUpperCase() === "POST" && $(this).find(":file").length === 0) {
		var formDataBkp = window.FormData;
		window.FormData = undefined;

		$("#my-pjax-container").on("pjax:beforeSend", function (options, xhr) {
			window.FormData = formDataBkp;
		});
	}

	var config = createMyCustomConfig();
	
	$.pjax.submit(event, "#my-pjax-container", config);
});
```


You can improve by implementing a common submit if you have an input file
