### ISSUE TITLE
Error message "timeout"

### ISSUE THREAD

**Issue by bnd170** [defunkt/jquery-pjax#540]
I just installed the library in my Symfony2 project .

This is the function that I'm using in the project.

``` javascript
            $(document).pjax('a', '#content-wrap', { 
                fragment: '#content-wrap', 
                timeout: 3000 
            }).on('pjax:send', function(){
                alert('success');
            }).on('pjax:error', function(e, xhr, err) {
                console.log('Something went wrong: ' + err);
                console.log(xhr);
            });;   
```

When I click on a link, I get the alert with "success" and a few seconds later I get the error console:

Something went wrong: timeout

**Comment by bnd170** [comment]
If i put timeout as 0, it works.

**Comment by staabm** [comment]
seems the url you are opening does not respond within 3000 mili-secs?

**Comment by mislav** [comment]
Like @staabm suggested, because you were using 3000ms as the timeout treshold and got the error with message "timeout", my initial guess would be that you actually got a… timeout error.

**Comment by jinmatt** [comment]
@bnd170 I was just going through the code, I think if timeout is set to 0, pjax doesn't check for a timeout. Not sure, have to check again.
