### ISSUE TITLE
Find the version

### ISSUE THREAD

**Issue by kafeltz** [defunkt/jquery-pjax#543]
Is there a way to find out the version of this plugin?

I could not find neither in the source code nor by $.pjax.defaults.version().

I want to keep track the version in my project in case my update goes wrong and I use the version to do.

**Comment by mislav** [comment]
The `defaults.version` property doesn't refer to the version of this library. There is no way to find out the version. There are several approaches you can take to figure out which version do you have. One approach is to look at your git history for when you vendored jquery-pjax.js. The date will help you match it to then-released version. Another approach is to update your vendored file with the latest version and use git diff to analyze the differences.

Finally, the best approach is to just update to the latest version and not think too much of it.

**Comment by jinmatt** [comment]
@mislav  or you can add to the bower.json the `version` similar to the package.json version followed by npm. The bower.json [specs](https://github.com/bower/bower.json-spec) mentions it has `version` property, but not in use as bower doesn't have a register as of now like the npm registry. 

N.B. But this is not a very essential feature, @kafeltz you can use the latest version always without thinking too much like @mislav mentioned.

**Comment by kafeltz** [comment]
Thanks for the answer.

I had to look the history in the project I'm working on to find out the version. It is really really old 1.0.0 (2012).

It's working fine until now. No breaking changes at the moment.
