### ISSUE TITLE
always aborted

### ISSUE THREAD

**Issue by ve3** [defunkt/jquery-pjax#544]
``` js
(function($) {
    $('.entry-content').on('click', '.pagination a, .pager a', function(e) {
        e.preventDefault();
        var paginate_link_val = $(this).attr('href');

        if (paginate_link_val !== '#') {
            $.pjax({url: paginate_link_val, container: '.entry-content'});
            console.log('pjax run');
        }

        delete paginate_link_val;
    });
})(jQuery);
```

console logged.
url request aborted. never work.

> http://localhost/wordpress/content/2/?_pjax=.entry-content Aborted 605ms

**Comment by mislav** [comment]
How long does your server need to send a response? It seems that it's not that fast. Try increasing the pjax timeout to a few seconds:

```js
$.pjax({
  url: paginate_link_val,
  container: '.entry-content',
  timeout: 2000
})
```

If it's not that, consider the possibility that some other code in your system can use Ajax hooks to abort requests. Based on just your code above, I can't tell exactly what's aborting the requests.
