### ISSUE TITLE
Scripts/code not firing on pjax:end, any thoughts?

### ISSUE THREAD

**Issue by richgcook** [defunkt/jquery-pjax#546]
Hi @mislav, thanks continually for a great plugin.

I'm running into a slight issue with refiring of scripts when pjax has finished/ended. If I refresh the browser on that page, the scripts work no problem, but on clicking/back (essentially with pjax is fired) my scripts never fire.

For example, I have this function,

``` js
function imageSizes() {
    $('.chronology-container .each-chronology .image-container, body.works-detail .image-container').each(function() {
        var div = $(this);
        var img = $('img', div);
        if ( img.height() < img.width() ) {
            div.addClass('landscape');
        } else {
            div.addClass('portrait');
        }
    });
}
```

And for pjax, I have:

``` js
$(document).on('ready pjax:end', function() {
    imageSizes();
    $('.loader').fadeOut();
});
```

But the script never works until I refresh... any thoughts? Am I doing this right? This is just one example, but things from isotope to custom scripts rarely fire on pjax. The weird thing is that the loader always fades out so I know it's doing something.

Cheers,
R

**Comment by mislav** [comment]
The event handler looks correct. You said the loader fades out after pjax has finished, so that means `imageSizes` definitely gets invoked. The problem probably lies within whatever that function is doing. Sprinkling logging or debugging statements in your code would be the fastest way to determine what's happening here and at which phase. Is anything stopping you from doing that?

**Comment by richgcook** [comment]
@mislav Thanks for the help. I'll dig around more if it's nothing obvious. Appreciated!

**Comment by richgcook** [comment]
@mislav I have to reopen this issue as I am really stuck with this. It's impacting on the rest of my scripts (sometimes fires, sometimes not... pretty inconsistent). Added a console.log statement to the `imageSizes` function shows it is being fired in the console; but it's clearly firing too early for the content. If I am using both `ready pjax:end` showed it show twice in the console? When exactly does pjax:end fire?

**Comment by mislav** [comment]
`pjax:end` fires after the XHR request fetching the new content has finished and new HTML has been injected into the DOM. I don't know what the problem of your app is since I don't see its full code nor understand exactly where the problem lies. “My scripts never fire” is a difficult problem to debug for anyone else other than you.

**Comment by richgcook** [comment]
Thanks for the reply. I really want to solve this so what would you like from me? What would help us figure out what is going wrong? I'll post some further code updates...

**Comment by richgcook** [comment]
Hi again @mislav...

Okay, so for example, at the top of my scripts.js file, I have lots of functions set up, an example of one is:

```
function imageSizes() {
	$('body.works-detail .image-container').each(function() {
		var div = $(this);
		var img = $('img', div);
		if ( img.height() < img.width() ) {
			div.addClass('landscape');
		} else {
			div.addClass('portrait');
		}
	});
}
imageSizes();
```

Then, after all this, I have two pjax setups; one for a click function, then one for any links with data-pjax.

```
$.pjax.defaults.scrollTo = false;
$.pjax.defaults.timeout = 200000;

if ($.support.pjax) {
	$(document).on('click', 'a[data-pjax-detail]', function(e) {
		e.preventDefault();
	    $('.loader').show();
	    $('body').removeClass('detail-loaded');
	    if ( $(this).is('.prev') ) {
		    $('body').addClass('detail-loading-prev');
	    } else {
			$('body').addClass('detail-loading-next');   
	    }
	    var url = $(this).attr('href');
	    $('#pjax.content').one(window.transitionEnd, function() {
	        $.pjax({
	            url: url,
	            container: '#pjax.content',
	            //fragment: '#pjax.content',
	            timeout: 200000
	        });
			if ( $('body').is('.detail-loading-prev') ) {
		    	$('body').removeClass('detail-loading-prev detail-almost-loaded-prev detail-loading-next detail-almost-loaded-next').addClass('detail-almost-loaded-prev');
		    } else {
				$('body').removeClass('detail-loading-prev detail-almost-loaded-prev detail-loading-next detail-almost-loaded-next').addClass('detail-almost-loaded-next');   
		    }
	    });
	});
	$(document).on('ready pjax:end', function() {
		$('body').removeClass('detail-loading-prev detail-loading-next').addClass('detail-loaded');
	});
}

$(document).pjax('a[data-pjax]', '#pjax.content');

$(document).on('ready pjax:start', function() {
	$('.loader').show();
});
$(document).on('ready pjax:end', function() {
	imageSizes();
	var bodyClass = $('meta[name=body-class]').attr('content');
	if (bodyClass !== undefined) { document.body.className = bodyClass; }
	$('.loader').fadeOut();
});
```

Hope this helps you realise my setup and if I am doing any particularly wrong? The issue I have is, for example, when I click on `data-pjax-detail` links, the `imageSizes` function states that it's firing with a console.log test, but it randomly says a portrait image, for example, is landscape and vice versa, then sometimes it is right and other times not so right. You see my issue... it's not consistent. This is one example using `imageSizes` whereas it's the same with any other function I have.

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
