### ISSUE TITLE
pjax and toggle/click states (resetting state for menus)

### ISSUE THREAD

**Issue by richgcook** [defunkt/jquery-pjax#547]
What's the best way to deal with collapsable menus (slideToggles or similar) specifically on mobile to remember open/close states?

If I click an icon (hamburger icon) to open the menu, and click the same icon to close, on loading the site, it works fine, but as soon as I click on a link to navigate to another page it loses its state and I get some odd results (but in fairness, true results) where it opens and closes in one click etc.

I was using slideToggle() before but thought I would use a class, so I can remove and add the class to open the menu and then reset the class on the AJAX callback once the pageload is successful...

I have something like this:

```
$('.menu-trigger').on('click touchstart', function(e) {
    var $this = $(this);
    if ($this.is('.non-active')) {
        $('.menu-trigger').addClass('active').removeClass('non-active');
        $('.menu').addClass('open');    
    } else {
        $('.menu-trigger').removeClass('active').addClass('non-active');                $('.menu').removeClass('open');
    }
});
$(document).on('ready pjax:end', function() {
    $('.menu-trigger').removeClass('active').addClass('non-active');
    $('.menu').removeClass('open');
});
```

Has anyone had any experience of this and perhaps how they got round it?

**Comment by mislav** [comment]
From the above code I can't really tell what's going on on your site. How about if you sprinkle some logging statements in your event handlers and try to interact with the hamburger menu?

**Comment by richgcook** [comment]
I actually think this is related to my other issue: https://github.com/defunkt/jquery-pjax/issues/546 where my init scripts aren't being fired properly.
