### ISSUE TITLE
Container appears twice

### ISSUE THREAD

**Issue by ilikourou** [defunkt/jquery-pjax#549]
Hello.

I am using jquery-pjax for an application and everything works fine, except for one thing.
This is the code so that you can understand what's the problem:

```
<div id="main">
    <div class="inner">
        .....
    </div>
</div>

.....

<script>
    $(document).pjax("a:not('[no-data-pjax]')", '#main');
    $(document).on('submit', 'form[data-pjax]', function(event) {
        $.pjax.submit(event, '#main')
    });
    $.pjax.defaults.timeout = 15000;
</script>
```

When I click on a link (inside #main), the new html code gets:

```
<div id="main">
    <div id="main">
        <div class="inner">
        .....
        </div>
    </div>
</div>
```

As you can see, div with id *#main* appears twice after the link is clicked.

Any help?

Thanks,
Ilias

**Comment by mislav** [comment]
Does the response HTML for the pjax request include `<div id="main">`? If so, then it's expected that it will appear twice. Pjax will insert anything that it receives as response HTML into the original `#main` container.

**Comment by ilikourou** [comment]
Yes, the response HTML does include `<div id="main">`, but what I don't understand is why response HTML starts from `<div id="main">` and not the the beginning of the document.

All my HTML pages have the following format:

```
<body>
    <div id="header">....</div>
    <div id="main">...</div>
    <div id="footer">...</div>
</body>
```

So, if everything received as response HTML gets into the original `#main` container, when a user clicks on a link inside `#main`, I would expect the HTML to become something like this:

```
<body>
    <div id="header">...</div>
    <div id="main">
        <div id="header">...</div>
        <div id="main">...</div>
        <div id="footer">...</div>
    </div>
    <div id="footer">...</div>
</body>
```

Is this correct?

Right now, only `<div id="main">` is inserted into the original `#main` cointainer.

Thank you,
Ilias

**Comment by ilikourou** [comment]
It turned out that using the **fragment** option made it work correctly:

```$.pjax.defaults.fragment = '#main';```

**Comment by mislav** [comment]
Glad you solved it! You should have closed the issue.
