### ISSUE TITLE
'Application Error' in http://pjax.herokuapp.com

### ISSUE THREAD

**Issue by kelly-apollo** [defunkt/jquery-pjax#551]
Demo site http://pjax.herokuapp.com is not working.

**Comment by mislav** [comment]
Thanks for reporting. @defunkt do you have access to the site?

**Comment by defunkt** [comment]
@mislav Yeah - just added you as a collab. Let me know if that's not helpful or there's something else I should do, haven't messed with it in forever.

**Comment by mislav** [comment]
Fixed the site by updating it to Heroku Cedar a6d1f55
