### ISSUE TITLE
pjax not working in EDGE browser

### ISSUE THREAD

**Issue by raj1205** [defunkt/jquery-pjax#552]
I am using Microsoft EDGE to test my product, where I use pjax plugin. It is mention in the document that browser which support push state will work with pjax and EDGE has the support but it is not working.

Can you please look into the issue.

**Comment by mislav** [comment]
Thanks for reporting. I will try to test once I obtain access to an EDGE browser. Are there any errors in the JS console when you try to use jquery-pjax? What is the effect you're seeing?

**Comment by raj1205** [comment]
I am getting syntax error pointing to jquery library at line number 559.

**Comment by szegheo** [comment]
I've just tested my project with Microsoft Edge 12.10240 (jQuery 1.11.3, pjax 1.9.6) and found no problem. Everything works as excepted, no errors.
