### ISSUE TITLE
Form submit with redirect does not replace the content

### ISSUE THREAD

**Issue by yefrem** [defunkt/jquery-pjax#553]
Hello. I'm trying to get login form submit working with pjax. I send it using $.pjax.submit and want to redirect user to the start page on successful login. When login is done I send content I want to see on start page and a header "X-PJAX-URL: /". But what I get is start page content inserted before the form (old html is not removed).

Another related question that may help to solve the first one: what is the correct way to make redirects. I expected that X-PJAX-URL header will make client request given URL and show content received in container and replace URL in browser. So on first attempt I didn't set any response body, but that caused full page reload. So I send content of the page I want to see in container and URL I want to see in address bar. This solution looks working but not logical for me and after I failed with form submit I started thinking I am doing it wrong.

UPD. That was my mistake making server return duplicated content so form submit works fine. But since I posted it can you please answer the second question?

**Comment by mislav** [comment]
Sorry for the late reply. Your usage of `X-PJAX_URL` seems correct. I hope you managed to implement what you were aiming for!
