### ISSUE TITLE
state.id when pjax:beforeSend was canceled

### ISSUE THREAD

**Issue by szegheo** [defunkt/jquery-pjax#557]
Hi!

I'm not sure if it's a bug or I'm doing something wrong: I'm using pjax for loading pages and modals into different containers. Every html response needs to be fresh, so caching is turned off with maxCacheLength = 0, but after a modal is closed I don't want the current page (under the modal) to be reloaded. For this I use event.preventDefault() in pjax:beforeSend. All is ok except when pressing forward again pjax does not do anything. Please check out my example to see this in action:

http://szegheo.github.io/pjaxtest/

As I see the problem is in the popstate handler of pjax where previousState.id is compared to state.id:
https://github.com/defunkt/jquery-pjax/blob/v1.9.6/jquery.pjax.js#L438

In my case these values are equal so the function exits there. When I comment out this line, my app works as excepted. Is it possible that some state id is not updated when request is cancelled at pjax:beforeSend?

**Comment by szegheo** [comment]
I think the problem is when beforeSend is cancelled, pjax.state is not updated, still has the data of the previous page. As I see it's only get updated in the options.success handler. This little hack to the options.beforeSend handler solves the problem, but I don't think it's the best solution for this:

```javascript
    if (!fire('pjax:beforeSend', [xhr, settings])) {
      if (window.history.state && window.history.state.id) {
        pjax.state = window.history.state
      }
      return false
    }
```

@mislav Any idea on this?

**Comment by mislav** [comment]
Your use-case is complex and I'm having a hard time following. I'm not sure that you should be even using pjax for stuff like modals. It also seems you want to hack around the corner you painted yourself into by cancelling pjax:beforeSend.

What is the expected behaviors you want to see with state IDs?

**Comment by dynasource** [comment]
> using pjax for stuff like modals

can you us why you dont think PJAX shouldnt be used for modals?

**Comment by mislav** [comment]
Pjax is a library to make navigation between pages happen quicker by avoiding reload of the page and instead replacing just the partial HTML of the page.

Modal dialogs are a UI pattern that has nothing to do with page transitions.

**Comment by dynasource** [comment]
thanx for your quick reply, although it is not satifying (yet) ;)
It is actually confusing because you're argument is one of the biggest reasons to combine both. 

Why shouldnt people use PJAX to replace partial HTMLs inside modals?

**Comment by mislav** [comment]
> Why shouldnt people use PJAX to replace partial HTMLs inside modals?

It's not that they strictly shouldn't. It's just that pjax wasn't designed for such a complex use case. Also, modal dialogs usually shouldn't create history entries to enable back-foward navigation between them. Pjax should be used when there is history to be preserved.

Anything preventing you to load up the HTML contents of the modal dialogs with plain Ajax and keep their implementation separate from pjax navigation?

**Comment by szegheo** [comment]
@mislav I think pjax is good for modals as it is. Sure, it needs some extra coding in event handlers but I'm fine with it. My only problem is that I think it HAS a bug, regardless of using for modals or normal pages:

The documentation says that pjax:beforeSend can be cancelled - so I'm using it - but it leads to a bug (when the next history change occurs). If this event is cancelled (during history change) pjax internally does not updates its pjax.state object for the current history item, instead it thinks that we are still on the previous page where we came from. That's why the very next back/forward click will do nothing because of this line of pjax code:

```javascript
      // If popping back to the same state, just skip.
      // Could be clicking back from hashchange rather than a pushState.
      if (previousState.id === state.id) return
```

One last thought on modals and urls: My bootstrap app has a products gallery. Every product has a unique (seo optimized) url. When I click on a product item it's details page opens in a big (80%) modal, but with the same url it can be viewed as a standalone page (e.g. right click on browser tab/duplicate). So if it's in a modal and the user presses back, I don't want the underlying page to be reloaded, so I need to stop that beforeSend event. That's the reason I need to use pjax for modals and to change the url when a modal (product) is open. Caching pages is not an option in my case, so $.pjax.defaults.maxCacheLength is 0.

Anyway, thanks for this great plugin and your support!
