### ISSUE TITLE
how can i use it reload html when the html is changed

### ISSUE THREAD

**Issue by easunlee** [defunkt/jquery-pjax#558]
hi, It is work good by pjax.
I use pjax for load html (not php)  and it is works very good until I change some html. 
with pjax, It is get old html just form cache not severs.
I check the options.version ,but this will hard load html just out ajax.
and I want check 'If-Modified-Since' for reload form sever and replace it in 'cacheMapping[id]' but it is not reload for sev just form cache.....
would you kind enough help me and tell How can I do ?

**Comment by mislav** [comment]
Hi, I'm afraid you can't do what you need from pjax right now. There's no mechanism to conditionally expire the in-memory cache that pjax maintains. Maybe the solution for you could be to disable pjax in-memory cache with `maxCacheLength: 0` and have navigation by Back button trigger re-fetches of the page. It will be slower, but at least it won't be stale.

**Comment by Eschwinm** [comment]
I think he has the same problem as I do, explained here : https://github.com/defunkt/jquery-pjax/issues/560
