### ISSUE TITLE
request "Aborted" - timeout

### ISSUE THREAD

**Issue by BrainFeeder** [defunkt/jquery-pjax#559]
I am using pjax for a while and did not have to many issues. But today we are trying to implement it for other links and it seems to be impossible somehow.

The application has the possibility to open a popup window (no modal) where users can find customer specific function (as in buttons / links / forms). Clicking a link (to eg tabular data view) should open the page in the application main browser window. We rewrote the working functions to following code to implement pjax

``` javascript
var target = $(window.opener.document).find('[data-pjax-container="true"]');
window.opener.$.pjax.click(e, {container:target});
```

The above is wrapped in `.on('click')` handler.

The page starts loading in the main browser but it immediatly recieves a timeout and the pjax fallback kicks in and does the full refresh. It can't be the timeout setting because it works when triggered from inside the main browser window.

(I asked a question on stackoverflow earlier which has a little more details:
http://stackoverflow.com/questions/32095230/pjax-click-from-in-a-pop-up-requests-timeout)

The request logs show 2 requests to the same page

```
bestellingen/toevoegen?tokenId=[sometoken]&_pjax=...    Aborted     0 B
bestellingen/toevoegen?tokenId=[sameAsAbove]            200 OK      62,1 KB
```

No idea why the first pjax request returns 0 bytes

**Comment by mislav** [comment]
Tricky. You seem to be doing things right, but then again the first pjax request gets immediately aborted for some reason. Unless your global timeout setting is really short (default is around 600ms), I don't think it's the timeout. Rather, is it possible that there is some other code in the main window that aborts ajax requests; e.g. cancels `pjax:beforeSend` event?

Please note that pjax wasn't designed for this kind of cross-frame scenario. Ultimately, I think it will be you who has the responsibility to debug this situation and make a call whether you want to insist on using pjax for this or just have the main window do a normal refresh as a workaround.

**Comment by BrainFeeder** [comment]
Thanks for the insights.. I'll have a look at the functions if somehow `pjax:beforeSend` gets cancelled.
It was just an attempt to only load a part of the page of the main window so all resources did not need to load again and we have this fancy 'loading indicator' during pjax events which we like too much. 

I'll post my future findings here for others who would like to use this.
