### ISSUE TITLE
Is a bug?

### ISSUE THREAD

**Issue by 308820773** [defunkt/jquery-pjax#561]
I send a pjax,  

When success and I click the back button(window.history.go(-1), then run the pjax:popstate callback.

But when error, and I click the back button,  pjax:popstate can't run.

**Comment by mislav** [comment]
What exact error happens after which you can't use the back button anymore?

**Comment by 308820773** [comment]
Yes, When click the back button , the url is changed. but the event not fired. (pjax:popstate,pjax:start,pjax:beforeReplace,pjax:end)

**Comment by mislav** [comment]
I was referring to this what you said:

> But when error, and I click the back button

What did you mean by "when error"?

**Comment by 308820773** [comment]
Sorry, 'when error' is mean, the pjax(ajax) is request error. (The server return the 404 or 500 status code. )

**Comment by szegheo** [comment]
@308820773 just a question to clean this situation:
Are you using your own error event handler?
Maybe you cancel the event there and this causes your problem.

@mislav If you cancel the error event (so the force reload) the same bug happens I mentioned in #557

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
