### ISSUE TITLE
Pjax and Yii2 redirect not working in Internet Explorer (IE11).

### ISSUE THREAD

**Issue by w3MediaLabs** [defunkt/jquery-pjax#562]
I am using the framework Yii2 with their implementation of Pjax.  The controller code adds a header "X-Pjax-Url" that is successfully passed with the response.

The redirect for Pjax is handled through the pjax.js methods just fine in Chrome, Safari, and Firefox, but fails in IE11.

When I use the included debugger and view the response headers, the header is there and the url is correct, but IE11 isn't reading it.

The response error:
![pjax-response-error](https://cloud.githubusercontent.com/assets/7306696/9570521/0d739eda-4f5c-11e5-9443-06877740d48f.jpg)

The response headers:
![pjax-response-headers](https://cloud.githubusercontent.com/assets/7306696/9570528/1b036990-4f5c-11e5-8019-9a1f8f7ff15b.jpg)

And here is two custom scripts attached to each page.  The timeout is needed on larger datatables, to prevent full page reloads.  I have since disabled the pjax:complete redirect as it is handled natively with pjax.js, but didn't realize it on the frontend.

```
    // pjax complete
    $(document).on('pjax:complete', function (event, xhr, textStatus, options) {
        var url = xhr.getResponseHeader('X-Pjax-Url');
        if (url) {
            window.location = url;
        }
    });
    // pjax timeout
    $(document).on('pjax:timeout', function() {
        return false;
    });
```

Any ideas?

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
