### ISSUE TITLE
Problems with URL in pjax

### ISSUE THREAD

**Issue by odanylevskyi** [defunkt/jquery-pjax#563]
Why pjax does not build new URL but add all variables to URL? It makes duplications such that:
before: 
localhost/ru/place/search?name=test
after pjax:
localhost/ru/place/search?name=test&name=newTest&image=12322&contains=
Please, help me with it.

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
