### ISSUE TITLE
pjax throws an error if form container a field with name action

### ISSUE THREAD

**Issue by iamwebdesigner** [defunkt/jquery-pjax#567]
If the `form` contains an input or any other form element which has the name attribute assigned with `action`, when submit button is clicked an error throwed on the console and everything is failed.
Sample html:
```html
<form action="/url/to/submit" data-pjax="1">
  <input type="text" name="action" value="delete"/>
  <input type="submit" value="delete"/>
</form>
```
Exception message: `Uncaught TypeError: url.replace is not a function`.  
Line: `jquery.pjax.js:591`.  
After some debugging I found the line causing such behavior:
```js
var form = event.currentTarget

  if (form.tagName.toUpperCase() !== 'FORM')
    throw "$.pjax.submit requires a form element"

  var defaults = {
    type: form.method.toUpperCase(),
    url: form.action, // <-- this line
    container: $(form).attr('data-pjax'),
    target: form
  }
```
https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L128  
Does it mean that we cannot use inputs with such name?

**Comment by iamwebdesigner** [comment]
There already has been created a pull request for this problem: https://github.com/defunkt/jquery-pjax/pull/554

**Comment by mislav** [comment]
Thanks for the ping. Closing in favor of the open PR.
