### ISSUE TITLE
Shopify

### ISSUE THREAD

**Issue by Panoply** [defunkt/jquery-pjax#569]
Hello!

I've had success with using PJAX-Standalone (https://github.com/thybag/PJAX-Standalone) version on Shopify. However integrating this version (jquery-pjax) does not seem possible. I believe this issue is because I am unable to set request.headers. 

If you are unable to set headers on server side will jquery-pjax fail? or am I missing something here?

**Comment by mislav** [comment]
Hi sorry for the late reply. Did you solve your issue? Are you asking how to set custom request headers with jquery-pjax?

**Comment by subir1910** [comment]
Hello!

Is jquery-pjax not working with shopify ?
