### ISSUE TITLE
PJAX form submit triggers full page reload on iOS

### ISSUE THREAD

**Issue by rreitmann** [defunkt/jquery-pjax#571]
Hi we are using PJAX to submit a search form and replace the result area with the search results (see https://metadatamanagement.cfapps.io/de/variables/search) On iOS (Chrome and Safari) we see that the page is fully reloaded instead of just the partial result area. Are there any known issues with PJAX form submit on iOS?

**Comment by staabm** [comment]
Usually PJAX reloads the whole page, when the server takes too much time to respond:

https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L876

**Comment by rreitmann** [comment]
I don't think it's a timeout because reload happens "immediately".

**Comment by rreitmann** [comment]
Hi, we have removed PJAX and implemented the partial loading of search results with jquery. The old version will be available for a while on https://testmetadatamanagement.cfapps.io/de/variables/search

**Comment by mislav** [comment]
There's no problems on iOS that I know of. Thanks for the info; I'll take a look when I can.

**Comment by socalengineer** [comment]
I also am experiencing this issue... it's only on Safari in IOS. It also happens even when I change the timeout to a much larger value in the options. But when I am using Google Chrome Developer mode with throttling set to 1000ms or higher it works fine, so it leads me to believe Safari on IOS is not respecting the ajax timeout for a form submit. Regular page GET requests are working fine. Is there any debugging information I could provide?

**Comment by abbychau** [comment]
I am also experiencing this issue.
iOS 9.3, safari.

**Comment by serussell** [comment]
Same thing.  Disabling timeout entirely doesn't help.  This only happens on Chrome -- the same code works fine on Firefox & Safari (El Capitan).  In all browsers, despite replacing a container, and having "push: false," the URL changes as well.

**Comment by iurisilvio** [comment]
I had the same issue with 1.7.0, just updated to 1.9.6 and it worked. Bissected to find which version fixed the issue for me. 1.9.2 has the issue, 1.9.3 works fine.

I don't know the codebase, but this is the change between these versions: https://github.com/defunkt/jquery-pjax/compare/cc0dd1...4d8f92

**Comment by mislav** [comment]
If this is still a problem, please reopen.
