### ISSUE TITLE
Navigating back in Chrome to PJAX site displays partial response

### ISSUE THREAD

**Issue by rreitmann** [defunkt/jquery-pjax#572]
We are using PJAX for submitting a search form and displaying the search results (see https://metadatamanagement.cfapps.io/de/variables/search). When we leave the pjax managed site by clicking on a search result and hit back afterwards Chrome displays the partial response which is not the complete html document. Are there any known issues?

**Comment by staabm** [comment]
Why do you use pjax to display the search result? Do you expect a user wants the "previous" search result when hitting browser back?

**Comment by rreitmann** [comment]
Yes, that is what we intend to do.

**Comment by mislav** [comment]
Without any demonstration or sample code we can't know what's going on here. Pjax is going to restore the previous contents of pjax container element that was cached before the navigation happened. Is a part of that contents from the container element missing? This needs more info. Thanks

**Comment by dkatzberg** [comment]
You can try the example in @rreitmann first comment. The code for this example is here: https://github.com/dzhw/metadatamanagement/blob/master/src/main/resources/static/js/variables/search.js 

We use the actual version of pjax from your github repository. https://github.com/dzhw/metadatamanagement/blob/master/src/main/resources/static/js/jquery.pjax.js

**Comment by rreitmann** [comment]
Hi, we have removed PJAX and implemented the partial loading of search results with jquery. The old version will be available for a while on https://testmetadatamanagement.cfapps.io/de/variables/search

**Comment by mislav** [comment]
Thanks for keeping the example up. I have taken a look in Chrome, but I can't reproduce what you're describing. I make a sample search, 3 items get displayed, and when I pick one item, navigate to it and back, I still see the same 3 results.

One thing I noticed was this:

```js
	// clone the event for the pjax api
	var clonedEvent = {};
	clonedEvent.currentTarget = event.currentTarget.form;
	clonedEvent.preventDefault = function() {};
	
	VariableSearchForm.throttledSubmit(clonedEvent);
```

combined with:

```js
VariableSearchForm.throttledSubmit = _.throttle(function(event) {
	$.pjax.submit(event, '#pjax-container');
},250);
```

`$.pjax.submit` was designed to accept the original `submit` event, not a cloned event or to be used in a throttled construct. It needs access to the original event synchronously because it needs to cancel it if pjax is supported, so that real form submit doesn't happen.

This is what might be causing #571

**Comment by rreitmann** [comment]
Hmm, currently I can't reproduce it as well. Maybe throttling is the key to this issue as well.

**Comment by mislav** [comment]
You definitely want throttling for live search, something that can be improved even in your new version without pjax, so I support you going the route of manual ajax requests. Pjax isn't strictly designed for live search results.

**Comment by rreitmann** [comment]
I have removed throttling thus the relevant parts of `search.js` now are:
```javascript
VariableSearchForm.search = function(event) {
	"use strict";

	//pjax needs the event which holds the form
	if (!event.form) {
		$.pjax.submit(event.originalEvent, '#pjax-container');		
	} else {
		$.pjax.submit(event, '#pjax-container');
	}
}; 
```
I have deployed that version to the test url mentioned previously. The problem mentioned in #571 still exists. This one I still cannot reproduce.

**Comment by mislav** [comment]
Closing stale implementation question. If you have a bug report, please open another issue with more information. Thank you!
