### ISSUE TITLE
Strange encoding in image's alt tag

### ISSUE THREAD

**Issue by ilikourou** [defunkt/jquery-pjax#573]
Hello.

I am having the following problem:

When a new page loads to Pjax container, everything works fine except for the images' alt tags, where their encoding changes. Our site's language is greek, and all the other text displays correctly, except for the images' alt tags. If I refresh the page, the alt tag displays also correctly, with the right encoding (utf-8).

I am using PHP's htmlentities function to generate the alt tag string, but I don't think this has something to do, since a hard refresh on the page displays all tags correctly.

Thanks,
Ilias

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
