### ISSUE TITLE
IE11 and  Edge , maxCacheLength:0 not work

### ISSUE THREAD

**Issue by Wizzercn** [defunkt/jquery-pjax#574]
chrome is ok.... firefox and other brower ?

jquery-1.11.1.min.js

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
