### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by Guro** [defunkt/jquery-pjax#575]
Is there an easy solution to implement progress on loading content via pjax?

**Comment by ApfelUser** [comment]
[nprogress](https://github.com/rstacruz/nprogress) +

```javascript
$(document).on('pjax:start', function() { NProgress.start(); });
$(document).on('pjax:end',   function() { NProgress.done();  });
```

**Comment by mislav** [comment]
There is no way to get incremental page loading progress with pjax.

**Comment by tyt2y3** [comment]
Pace works out-of-the-box for Pjax
https://github.hubspot.com/pace/docs/welcome/
