### ISSUE TITLE
X-PJAX-URL

### ISSUE THREAD

**Issue by Guro** [defunkt/jquery-pjax#577]
Hello we are using .htaccess with modrewrite to do some url rewriting.
so the problem is for example we have url:

/news/item/5 which actually rewrites via htacces to something like mode=news&id=5
so when pjax is imlemented and link is set to /news/item/5 it refreshes whole page, but if link is set to 
?mode=news&id=5 everything works fine.

i think its related to X-PJAX-URL header but documentation is unclear at this point, can anyone help?

**Comment by kafeltz** [comment]
As far as i know, the header have nothing to do with URL in this case.

See your response of your pjax and check for http 302 status or location attribute.

Seems to be some callback logic.

**Comment by staabm** [comment]
@Guro PJAX doesnt know anything about your server-side magic. it is only aware of urls on the client-side and it expects `X-PJAX-URL` to be formatted like the urls it uses for navigation.

**Comment by Guro** [comment]
Sorry the problem was in absolutely different thing :) my fault
