### ISSUE TITLE
Unspecified error in IE10 iframe

### ISSUE THREAD

**Issue by mstijak** [defunkt/jquery-pjax#579]
I just want to report the problem I encountered.

Plugin script throws `Unspecified error.` exception if loaded from iframe in IE10.

The exception is thrown on line: 

```
initialState = window.history.state;
```

As a quick fix I changed it to:

```
try { 
    initialState = window.history.state;
}
catch (e) { }
```

IE11 works fine.

**Comment by mislav** [comment]
Thanks for reporting! We won't be fixing IE10 issues, though, since that browser is very old. It's good to know that this bug doesn't exist in IE11 and above.
