### ISSUE TITLE
X-PJAX-URL redirect missing X-PJAX header

### ISSUE THREAD

**Issue by Steinweber** [defunkt/jquery-pjax#580]
If I get a request from pjax, I check eg whether the user is logged on or he has the permission to access. If the users do not have access, I redirect him. For this purpose, I use X-PJAX URL: {new_url} header.
Unfortunately, the new URL is not called with an X-PJAX = true header, which means that the page is displayed as a normal request. But i like to request \login.html with pjax. 
Is there a solution?

**Comment by Steinweber** [comment]
I added this on pjax - options.success
```javascript
var redirect = xhr.getResponseHeader('X-PJAX-URL');
            if(redirect && !container.contents){
                pjax({url: redirect, container: options.context})
                return;
            }
```

**Comment by mislav** [comment]
You probably don't need to change any client code here. Instead, simply redirect normally on the server. Example:

```
GET /mypage
X-PJAX: true

HTTP 302 Found
Location: /login.html

# ajax will automatically follow the 302:
GET /login.html
X-PJAX: true

# login page should set X-PJAX-URL to its own url:
HTTP 200 OK
X-PJAX-URL: /login.html
```

XMLHttpRequest (which pjax is based on) will automatically follow redirects. Hopefully it will preserve the same headers as well.

**Comment by mislav** [comment]
Let me know if that worked!

**Comment by Steinweber** [comment]
It works only partially. It is loaded to the right content, but the URL is not changed.
Example:
#### Request
>Request URL:http://example.com/setting/profile
>Request Method:POST
>X-PJAX:true
>X-PJAX-Container:#content
>X-Requested-With:XMLHttpRequest

if the data invalid, i return new content (form with errors)
if the update is success, i just send new header

#### Response
>Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
>Connection:Keep-Alive
>Content-Length:0
>Content-Type:text/html; charset=UTF-8
>Location:http://example.com/setting/setting
 
The content from setting/setting ist displayed, but the url is setting/profile

#### My solution
I changed the response in my redirect
```php
public function redirect($url, $status = 302) {
		if (isset($_SERVER['HTTP_X_PJAX'])) {
			header('X-PJAX-URL: '.$url,true);
			exit();
		}
		header('Location: ' . $url, true, $status);
		exit();
	}
```
and added this to the pjax.js

```javascript
var redirect = xhr.getResponseHeader('X-PJAX-URL');
            if(redirect && !container.contents){
                pjax({url: redirect, container: options.context})
                return;
            }
```
In this solution, i didn´t send a status 302. Just the new URL.
This will work for me

**Comment by mislav** [comment]
> The content from setting/setting ist displayed, but the url is setting/profile

You could have fixed that by having `setting/setting` page set the `X-PJAX-URL` response header:

    X-PJAX-URL: /setting/setting

**Comment by Steinweber** [comment]
The X-PJAX-URL header does not change the url...

**Comment by mislav** [comment]
How are you setting it from the server, can I see the line of code? Is it set from a response from `setting/setting` page? Thanks
