### ISSUE TITLE
Pjax reload() does not fire any events.

### ISSUE THREAD

**Issue by osCMattiFinn** [defunkt/jquery-pjax#582]
I am using Pjax in a Yiii2 project.

I am testiing an "Export" button to reload a gridview with extra parameters.

The gridview loads as expected, however Pjax does not fire any events such as "complete", "end", "success" etc.  The alert in the below example does not fire, no matter which event is used:

``` javascript
    $("#export-button").click(function() {
        $.pjax.reload({container:"#w0", 
            timeout: false,
            complete: function() {
                alert("success");
            },
            data: $("#labelForm").serialize()+"&export=true&class=label",
        });
        return false;
    });
```

**Comment by acorncom** [comment]
See https://github.com/defunkt/jquery-pjax/issues/424  Believe this issue can be closed

**Comment by mislav** [comment]
Yes; see referenced issue for a workaround.
