### ISSUE TITLE
Mysterious line that doesn't do anything

### ISSUE THREAD

**Issue by patrickmestabrook** [defunkt/jquery-pjax#585]
Should there be something happening here?  It would appear that this line probably doesn't accomplish what the comment above it says it should.

https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L495

**Comment by mislav** [comment]
It does accomplish what the comment describes. Simply accessing the clientLeft property triggers a reflow in browsers. Please see http://mislav.uniqpath.com/2014/02/hidden-documentation/
