### ISSUE TITLE
it screws with my pdf links

### ISSUE THREAD

**Issue by Evertt** [defunkt/jquery-pjax#589]
It turns these links:

```html
<a class="download" href="/artists/banksy/works/5404.pdf">Download factsheet</a>
```

Into this:

```html
<a class="download" href="/artists/banksy/works/5404?_pjax=%23pjax-container.pdf">Download factsheet</a>
```

How do I stop it from doing that?

**Comment by mislav** [comment]
Hi, pjax doesn't rewrite any links in the DOM.

Does your server maybe try to preserve `_pjax` param in generated links because it received one in a pjax request?

**Comment by Evertt** [comment]
Shit you are right, my laravel middleware causes the problem...
Damn

**Comment by mislav** [comment]
Thanks for the update!
