### ISSUE TITLE
Pjax and vBulletin

### ISSUE THREAD

**Issue by ilikourou** [defunkt/jquery-pjax#592]
Hello.

I've been searching for days but couldn't manage to find something: Is there an easy way to use Pjax in a **vBulletin 4.x** (http://www.vbulletin.com/) board?

My main site already uses Pjax without any issues and I am trying to have Pjax in my vBulletin pages as well. For my main site (built with Laravel) I have used a Pjax plugin to handle the server-side configuration, but what about vBulletin? Do I have to set _X-PJAX_ header for pjax to work? And if so, where do I set this header?

Thanks,
Ilias

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
