### ISSUE TITLE
maxCacheLength

### ISSUE THREAD

**Issue by demimurych** [defunkt/jquery-pjax#593]
maxCacheLength can only be SET with $.pjax.defaults.maxCacheLength

$(document).pjax('nav a, a.pjax', '#main_cont', {maxCacheLength:1, scrollTo: false, timeout: 30000}); -
nothing

**Comment by Jaskey** [comment]
Found the same issue,  it seems the maxCacheLength option is never used, instead, it always uses the defaults.maxCacheLength.
```
function cachePop(direction, id, value) {
  ......
  // Trim whichever stack we just pushed to to max cache length.
  trimCacheStack(pushStack, pjax.defaults.maxCacheLength)
}
```

function cachePush(id, value) {
   .....
  // Trim back history stack to max cache length.
  trimCacheStack(cacheBackStack, pjax.defaults.maxCacheLength)
}

The custom maxCacheLength should be respected.

**Comment by mislav** [comment]
It's true, `maxCacheLength` can only be used from defaults. This is the way the option was designed. Being able to set `maxCacheLength` per request would lead to unpredicable results.
