### ISSUE TITLE
can't cancel event  in popstate to stop following pjax event

### ISSUE THREAD

**Issue by Jaskey** [defunkt/jquery-pjax#598]
I need to dymatically re-send request at pjax:popstate event to init my page and do not need the cache content loaded any more. 

But I can't control pjax event at popstate to stop following pjax event like "start, beforeReplace".
I tried `return false` or  `e.preventDefault()` does not stop the following actions.

```
   $(document).off('pjax:popstate').on('pjax:popstate', function(e) {
       console.log('[pjax:popstate]',e);
       //window.location.href=e.state.url;
       $.ajax({
           url: e.state.url,
           type: "get",
           success: function (data) {
               //console.log('ajax success',$(data));
               _pageinit(data);//init my page again, no need for cache content
           }, error: function (xhr, textStatus, error) {
                console.log(xhr.status);
           }
       });

       e.preventDefault();//not work
       return false;//not work
   });
```

**Comment by mislav** [comment]
You can't cancel the `pjax:start` or `pjax:beforeReplace` events. Pjax isn't designed to have these features.
