### ISSUE TITLE
Pjax with single  concatenated/uglified js file

### ISSUE THREAD

**Issue by roundge** [defunkt/jquery-pjax#600]
HI there, 

Just to be sure I'm on the right way, 
I created an application with Symfony2 and want to integrate a pjax navigation.
I use gulp to concatenate and uglify js files.

Pjax works very fine. But when previous page is called, pjax load cached page and doesn't re-eval scripts, Isn't it ? 

My question :  to solve this problem, using ```$(document).on('ready pjax:success', function(){...})``` on the events is a good solution ?

**Comment by staabm** [comment]
Right you are.

**Comment by roundge** [comment]
mmmm ok. Thanks ;)

**Comment by mislav** [comment]
To do something after every pjax navigation, including Back/Forward browser buttons, you can listen for the `pjax:end` event. See events documentation in the README for more information. :wink:
