### ISSUE TITLE
strange subpage pagination is a PJAX issue or not?

### ISSUE THREAD

**Issue by JJ2** [defunkt/jquery-pjax#601]
pjax on main page tuned as:
$(document).pjax('#page a:not([data-static=true])', '#center',{'fragment':'#center'});

main site - pagination and links on page - work fine
from first page on main, next link mouse tap:
[10/Dec/2015:17:28:20 +0300] "GET /page-2/?_pjax=%23center HTTP/1.0" 200 29532
[10/Dec/2015:17:28:22 +0300] "GET /page-3/?_pjax=%23center HTTP/1.0" 200 29106
[10/Dec/2015:17:28:24 +0300] "GET /page-4/?_pjax=%23center HTTP/1.0" 200 28121

but for subpages (http:/site/somecategory/page-2 etc) we have so:

first subcategory page / next link mouse tap:
[10/Dec/2015:17:27:52 +0300] "GET /somecategory?_pjax=%23center HTTP/1.0" 301 8
[10/Dec/2015:17:27:52 +0300] "GET /somecategory/ HTTP/1.0" 200 28924

eventually we get always first page of subpage for subpage pagination with pjax 

needed 
[10/Dec/2015:17:27:52 +0300] "GET /somecategory/page-2/?_pjax=%23center HTTP/1.0" 200 28121

pagination is fine for all pages and subpages for disabled pjax

in general:
pagination links like "http:/site/page-x" works fine
pagination links like "http:/site/xxx/page-x" is not work!
pagination links like "http:/site/xxx/xxx/page-x" works fine

why this happening?

**Comment by JJ2** [comment]
gyus? nobody knows? :-/

**Comment by mislav** [comment]
Sorry that this hasn't got any attention. I don't see why pjax wouldn't work for subpages, but then again, you didn't share any markup from your site. Is it possible that pjax was misconfigured?

**Comment by JJ2** [comment]
mislav, you can look what i mean http://helionews.ru/
a forum - is fine (http://helionews.ru/forum)
main pagination is work fine - sub pagination - is not ( http://helionews.ru/kosmos )
still I do not understand why it is so ...

**Comment by JJ2** [comment]
ps - pagination is a links like '1 2 3 4 5 6 7 8 9 10 ... 10xN' at top pages

**Comment by JJ2** [comment]
settings for pagination (not a forum)
    $.pjax.defaults = {
        timeout: 3000,
        push: true,
        replace: false,
        type: 'GET',
        dataType: 'html',
        scrollTo: 0,
        maxCacheLength: 66
      };
        $(document).pjax('#page a:not([data-static=true])', '#center',{'fragment':'#center'});

**Comment by mislav** [comment]
@JJ2 I click on the subpagination links and the correct request gets made:

```
GET /kosmos/page/2/?_pjax=%23center HTTP/1.1
Host: helionews.ru
Accept: text/html, */*; q=0.01
X-Requested-With: XMLHttpRequest
X-PJAX: true
X-PJAX-Container: #center
```

However instead of a HTTP 200 response, I get a redirect to `/kosmos/`:

```
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=UTF-8
Location: /kosmos/
Access-Control-Allow-Origin: *

Redirect
```

So, pjax is configured correctly in the browser; it's just that the server keeps re-rendering the same initial page all over again, without fetching any new pages.

I'm sorry, but this is a server problem. I recommend that you first implement pagination links without pjax, make sure that works, and add back pjax as a final step.

**Comment by JJ2** [comment]
all pagination links is work fine without pjax ....
