### ISSUE TITLE
Cache the request and on back button, use the cached data instead of reloading it?

### ISSUE THREAD

**Issue by rotaercz** [defunkt/jquery-pjax#603]
This isn't a bug. It's a question but I wasn't sure where to ask.

Is there an easy way to cache the request then on browser back button, use the cached data instead of reloading it? The reason I ask is when using an infinite scroll page and when the user selects something from there, say it loads the contents on top however when the browser back button is clicked the infinite scroll page gets reset and the user has to start scrolling down from the beginning again.

**Comment by dkfiresky** [comment]
@rotaercz you better ask this question at stackoverflow.
Probably you should save page scroll position to cookie (local storage etc.) and then restore (automatically scroll to that position) it or something like that.

**Comment by mislav** [comment]
When browser Back button is used after a pjax navigation, pjax will handle that by restoring previous page contents from an in-memory cache. There should be no page reload happening on browser Back navigation with pjax unless the pjax cache is disabled.
