### ISSUE TITLE
$(document).pjax('a', '#pjax-container')  in document is not working

### ISSUE THREAD

**Issue by rgblite** [defunkt/jquery-pjax#606]
$(document).pjax('a', '#pjax-container') not working
the code must contain timeout option ,like :
$(document).pjax('a', '#pjax-container',{timeout:10000})

**Comment by mislav** [comment]
The default timeout of 650ms likely wasn't enough for your server to reply, so you had to increase it. This is expected behavior and not a bug of pjax. That's why the configuration option is for!

Thanks for letting people know of the workaround, though.
