### ISSUE TITLE
jQuery pjax not working when I reload the page. Head footer other boy content gone

### ISSUE THREAD

**Issue by Subhojit1992** [defunkt/jquery-pjax#608]
Hey Defunkt,
Please kindly give me a solution for this stackoverflow question.
http://stackoverflow.com/questions/34959706/jquery-pjax-not-working-when-i-reload-the-page-head-footer-other-boy-content-go
if need a demo I can also provide that.

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
