### ISSUE TITLE
pjax unbind 'submit' event?

### ISSUE THREAD

**Issue by eldyvoon** [defunkt/jquery-pjax#610]
after navigate with pjax, I found below binding event has gone. 

`$(document).on('submit', 'form[method="POST"]', function(event) {
alert('something');
});`

while this binding is still 'live'

`$(document).on('click', '.test', function(event) {
alert('test');
});`

This is annoying.

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
