### ISSUE TITLE
Google Tag Manager pushState/replaceState

### ISSUE THREAD

**Issue by koenpunt** [defunkt/jquery-pjax#611]
_From @koenpunt on January 25, 2016 16:31_

On a regular page load, bothe `pushState` and `replaceState` are called, which causes duplicate page views in the Google Tag Manager for the event "History change".

Is this intentional? Or is there something I missed in the configuration?

_Copied from original issue: rails/pjax_rails#79_

**Comment by koenpunt** [comment]
Could the error be on this line: [jquery.pjax.js#L291](https://github.com/rails/pjax_rails/blob/master/vendor/assets/javascripts/jquery.pjax.js#L291)

Where it maybe should be:

```js
if (!options.push || options.replace) {
```

**Comment by mislav** [comment]
Sorry, I don't know what Google Tag Manager is! But you're right that both `pushState` and `replaceState` are called. This is for technical reasons. This should't be a problem because the library works fine this way.

**Comment by koenpunt** [comment]
Maybe not a problem for the library, but can be for where it's implemented. I can't recall right away how I worked around this, since it has been more than a year, but I'll get back to this topic. 

And google tag manager is the de facto standard of managing tracking scripts, analytics and other measuring tools. So having duplicate impressions there due to a library is a problem.

https://www.google.com/analytics/tag-manager/

**Comment by jpburn** [comment]
@koenpunt  @mislav Any updates on how you used Pjax and Tag Manager? I'm facing the same problem and would like to fix it for future projects.

Thanks
