### ISSUE TITLE
multiple fast clicks on a link load the page without pjax

### ISSUE THREAD

**Issue by elkebirmed** [defunkt/jquery-pjax#612]
Even in the heroku demo for the pjax plugin, the page will load manualy if you clicked multiple times with fast (before the pjax complete the process)

any solution for this?

**Comment by mislav** [comment]
The effects of pjax when a link has been clicked multiple times quickly are unpredictable. However, this is not how people commonly interact with web pages, so we think that it's fine to leave it that way. If the worst case scenario is that a normal page load will be performed, I think that's fine and not a problem with the pjax library, as long as most others page transitions are performed over ajax.
