### ISSUE TITLE
No NPM installation?

### ISSUE THREAD

**Issue by Jamesking56** [defunkt/jquery-pjax#615]
Hello,

Tried to do `npm install jquery-pjax --save` and it says the package doesn't exist... Are you enforcing Bower?

**Comment by eberkund** [comment]
I would also be interested in using NPM, all the packages I use are available on NPM as well as Bower so I'd rather not use an extra package manager for no good reason.

**Comment by christophwolff** [comment]
+1

**Comment by barbuslex** [comment]
+1

**Comment by timfcsm** [comment]
you can install it from github
`npm i -D https://github.com/defunkt/jquery-pjax.git`

**Comment by mislav** [comment]
https://www.npmjs.com/package/jquery-pjax
