### ISSUE TITLE
Get multiple fragment?

### ISSUE THREAD

**Issue by JJ2** [defunkt/jquery-pjax#619]
have more one a question. how update main site fragment ("the page") and another fragment (bread crumbs for example, located outside "the page" fragment) by one pjax event?
v1:
            $(document).pjax('#page a[data-pjax]', '#center', {'fragment':'#center'});
            $(document).on('click', 'a[data-pjax]', function(event) {
                var container = $('#sbar');
                $.pjax.click(event, {container: container});
            });
v2:
            $(document).on('click', 'a[data-pjax]', function(event) {
                var container = $('#sbar');
                $.pjax.click(event, '#sbar', {'fragment': '#sbar'});
                $.pjax.click(event, '#center', {'fragment':'#center'});
            });
isn't work

**Comment by JJ2** [comment]
excuse me for a double, i go to read Multiple Pjax Containers thread now :)

**Comment by s-kias** [comment]
same issue

**Comment by mislav** [comment]
Pjax only helps you replace content in one container element (that's what it was designed for). For multiple containers or content replacements on the page at once, you'll need to write some custom javascript for your website. We can't help you with that. I hope you had luck with this!
