### ISSUE TITLE
PHP / Codeigniter + PJAX -- URL not updating after form submit

### ISSUE THREAD

**Issue by schester44** [defunkt/jquery-pjax#620]
After successful login, this should redirect the user to localhost/u/username and should change the URL to localhost/u/username. The correct view is being loaded however the URL is not changing. From the searching i've done, I seem to not be the only one with this issue. What am I doing wrong?

```

if ($this->ion_auth->login($this->input->post('identity'), $this->input->post('password'), $remember)) {
//if the login is successful

$this->output->set_header('X-PJAX-URL: ' . base_url('u/' . $this->ion_auth->user()->row()->username));

$this->output->set_header('Location: ' . base_url('u/' . $this->ion_auth->user()->row()->username), false);

} 
```

`$(document).on('submit', '.login-form', function(event) {
    console.log('PJAX FORM SUBMIT');
    event.preventDefault();
    $.pjax.submit(event, selector.main, {"timeout": 5000, "scrollTo": 0, maxCacheLength: 0});
})`

**Comment by socalengineer** [comment]
I found my problem, we are not setting the X-PJAX-URL header, this is required on every page. You can see my issue I had the same problem:
https://github.com/defunkt/jquery-pjax/issues/629

**Comment by nosecdev** [comment]
Hi, dont set X-PJAX-URL on your login controller (page) but.. set X-PJAX-URL header on localhost/u/username page :dancer: 

It's working on my Codeigniter project

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
