### ISSUE TITLE
Append URL without Loading Any Content

### ISSUE THREAD

**Issue by tetrahydra** [defunkt/jquery-pjax#621]
Hello,

This is my situation:
1. Form contents are submitted using normal ajax.
2. If successfully saved, it will return DocumentID

How can I append the **DocumentID** to the URL without reloading the whole page?

New document: **/form.php**
Edit document: **/form.php?docid=14**
After saving the document, I would like to append similar to Edit document URL format.

How can achieve this with pjax?

Would be great if someone can point me how to do this.

Thank you.

**Comment by staabm** [comment]
You either need to submit the form with pjax instead of ajax or consider using the browsers history api

**Comment by tetrahydra** [comment]
Let see for example:

```
$.ajax({  
		type     : "POST",  
		url      : "form_submit.php",  
		data     : dataString,  
		dataType : "json",
		success  : function(response) {
			docid = response.docid;
```

If i am using pjax to submit this form, will it not change the url from **/form.php** to **/form_submit.php** ?

The DocumentID that I am intended to use is being returned by form_submit.php

**Comment by staabm** [comment]
You can make pjax to change the url to whatever you like using  a `X-PJAX-URL` response header.

See https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L695

**Comment by tetrahydra** [comment]
superb! i will try to amend the code first. just to confirm, can i set my header like this?

`header('X-PJAX-URL:' . '?docid=' . $docid);`

**Comment by staabm** [comment]
Yep

**Comment by tetrahydra** [comment]
i am using this method for my sub-content area, but if i leave it empty, it doest work. I need to give value in the header

`header('X-PJAX-URL:');`

`header('X-PJAX-URL:dashboard');`

this the command i am using to invoke:

`$.pjax({url: 'dashboard_recent_addition', container: '#recent_addition'});`

because it is a sub-content, i do not want to update the URL.

And i would like to show a loading div, so, how can I bind `$(document).on('pjax:start'` into a `$.pjax`

**Comment by mislav** [comment]
Specific implementations of pjax in your own applications are left as an exercise to the reader. I hope that by now, you have accomplished what you needed with pjax!
