### ISSUE TITLE
Google AdSense with PJAX. How?

### ISSUE THREAD

**Issue by JJ2** [defunkt/jquery-pjax#622]
Google says:

"
AdSense For AJAX
We're no longer accepting new applications for AdSense for AJAX, but we appreciate your interest in the product and will continue to work on new ways to monetize dynamic content.
"

GoogleAds script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"

-- in HTML head and function in PJAX event

function displayGoogleAds(){
        $('ins').each(function(){
                    (adsbygoogle = window.adsbygoogle || []).push({});
        });
}

says: Uncaught ReferenceError: displayGoogleAds is not defined
or 
Uncaught TagError: adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.

But a PJAX is not totally dinamic AJAX. All pages have Html versions. How to work with this policy

thread at a google forum
https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/webmasters/JqWA0pZnJiA/Dc70dRzBAAAJ

**Comment by mislav** [comment]
Sorry, I have no experience with AdSense. I hope you have figured out how to make this integration on your own!
