### ISSUE TITLE
Increase progress manually

### ISSUE THREAD

**Issue by kamov** [defunkt/jquery-pjax#623]
I see that we can show progress bar using pjax:start and pjax:end,
but is possible to increase progress manually?

I know that I need to send from server this info, but how to catch this with pjax?

Thanks

**Comment by kamov** [comment]
I see this post:
http://www.dave-bond.com/blog/2010/01/JQuery-ajax-progress-HMTL5/

but not sure how to implement with pjax

**Comment by giantomakin** [comment]
@kamov try this http://github.hubspot.com/pace/docs/welcome/

**Comment by kamov** [comment]
Thanks, but this is not really file progress, but any ajax progress. I have already integrated this, but when file is uploaded, this is not show, until the end of file uploaded.

**Comment by mislav** [comment]
There isn't any way to show incremental page loading progress using pjax.
