### ISSUE TITLE
pjax seems to be caching loaded content (page not updating)

### ISSUE THREAD

**Issue by nickleus** [defunkt/jquery-pjax#628]
i click a "publish" btn on my page which should reload only a content div, where the "go to site" btn should now be enabled (php if-block inside html template that sets "go to site" btn enabled if a var == "1"), but the btn doesnt get enabled.

interestingly enough, when i put a debug breakpoint in the php code in my html template (which causes a delay during execution time, obviously) THEN the "go to site" btn is rendered properly.

ideas?

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
