### ISSUE TITLE
Difference between PJax defaults (PHP widget and JQuery)

### ISSUE THREAD

**Issue by almirb** [defunkt/jquery-pjax#630]
Hi!

I'm using pjax for erasing values of my gridview. But after the request the page always scrolls to top. That's annoying....
After a little research, I discovered I could overcome the problem with

``` js
$.pjax.defaults.scrollTo = false;
```

Why the Yii Pjax Widget (yii\widgets\Pjax) has the 'scrollTo' default value = false and in jquery.pjax.js the defaults are definied with 'scrollTo: 0'?

In jquery.pjax.js (around line 920):

``` js
// Install pjax functions on $.pjax to enable pushState behavior.
//
// Does nothing if already enabled.
//
// Examples
//
//     $.pjax.enable()
//
// Returns nothing.
function enable() {
  $.fn.pjax = fnPjax
  $.pjax = pjax
  $.pjax.enable = $.noop
  $.pjax.disable = disable
  $.pjax.click = handleClick
  $.pjax.submit = handleSubmit
  $.pjax.reload = pjaxReload
  $.pjax.defaults = {
        history: true,
        cache: true,
    timeout: 650,
    push: true,
    replace: false,
    type: 'GET',
    dataType: 'html',
    scrollTo: 0,       <----- HERE
    maxCacheLength: 20,
    version: findVersion,
    pushRedirect: false,
    replaceRedirect: true,
    skipOuterContainers: false,
    ieRedirectCompatibility: true
  }
  $(window).on('popstate.pjax', onPjaxPopstate)
}
```

Thanks in advance! 

P.S.: I also created a [post in Yii Forum](http://www.yiiframework.com/forum/index.php/topic/71190-difference-between-pjax-defaults-php-widget-and-jquery/).

**Comment by socalengineer** [comment]
This doesn't look like a bug or issue to me, different people have different tastes. Set your defaults to what you like them to be.

**Comment by mislav** [comment]
The default is scrolling to the top because that's how browser navigation usually works: when you change the page, you're brought to the top of the new page. However, you can change the default yourself, as you already found out, or you can specify the `scrollTo` value for every individual `$.pjax` call if you need to.
