### ISSUE TITLE
pjax duplicating bug on back & forward

### ISSUE THREAD

**Issue by ctf0** [defunkt/jquery-pjax#632]
the duplication happens when u move back & forward, it also happens only if there were any `ul, li` are being created dynamically, 
like a drop down 
https://silviomoreto.github.io/bootstrap-select/
or an image slider
https://github.com/sachinchoolur/lightslider 

i dont know how to disable pjax on back/forward to avoid that or even better how to address the troubling code ? 😢

**Comment by stereosteve** [comment]
pjax does internal caching that causes problems.

Set `$.pjax.defaults.maxCacheLength = 0` to force pjax to always fetch content.

See https://github.com/defunkt/jquery-pjax/issues/482#issuecomment-220047191

**Comment by ctf0** [comment]
sweet, problem solved :+1: , many thanx
