### ISSUE TITLE
Manipulating push-State

### ISSUE THREAD

**Issue by Nickolaus** [defunkt/jquery-pjax#633]
In my project I am replacing the current content with a loading indicator in the `beforeSend` event, this however causes pjax to show the loading indicator after the content has changed and I go back in history, is there some way to manipulate the steps I want to go in the history (Can I always make 2 steps instead of 1)??

**Comment by mislav** [comment]
The correct solution to this would be to show the loading indicator outside of the container element. That way, the loading indicator won't be cached as part of previous page contents, and won't be restored on browser Back navigation.
