### ISSUE TITLE
Not working Pjax if i use html tag <object>

### ISSUE THREAD

**Issue by semiromid** [defunkt/jquery-pjax#635]
Not working Pjax if i use html tag <object>

`<object style="height: 45px;" class="data-pjax cell-fluid-school" type="image/svg+xml" data="/basic/web/assets/build/images/ic_school_white_24px.min.svg" >`

Why?

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
