### ISSUE TITLE
Use virtual-dom to insert content

### ISSUE THREAD

**Issue by staabm** [defunkt/jquery-pjax#636]
Would it make sense to use a virtual-dom[1] to bring the html which we got from the server side and put it into the DOM tree? I guess there could be some savings like less DOM operations and maybe off-the-dom-tree style calculations which we could benefit from (maybe in a WebWorker).

The best summary of what all the virtual-dom libs are trying to achieve is https://gist.github.com/Raynos/8414846

I am no virtual-dom expert, so take this with a grain of salt.

[1] https://github.com/Matt-Esch/virtual-dom or https://github.com/trueadm/inferno or ...

**Comment by mislav** [comment]
Thanks for suggesting! Pjax currently does a very simple insert of contents into a container element. I think using a virtual DOM in this case would be an overkill. Furthermore, this library will probably not receive future features and enhancements.
