### ISSUE TITLE
pjax.click work twice

### ISSUE THREAD

**Issue by yahorosh** [defunkt/jquery-pjax#639]
use standart code from docs 

```
   if ($.support.pjax) {
        $(document).on("click", "#load-data", function(e) {
            var container = $(this).closest("[data-pjax-container]");;
            $.pjax.click(e, {container: container, push: false});
         });
    };
```

i see that request sendig twice. 

First from my anonimus function
![pjax1](https://cloud.githubusercontent.com/assets/3594651/16836566/d517f20a-49c6-11e6-932d-bde1f067a402.png)

Second from jquery.pjax.js:47
![pjax2](https://cloud.githubusercontent.com/assets/3594651/16836576/e3639a44-49c6-11e6-99c2-71eea2a12cc7.png)

**Comment by kmmbvnr** [comment]
did you try to add `return false` to the anonymous function?

**Comment by fari-99** [comment]
@yahorosh what do you want this click for? if you want to submit a form, you can try @kmmbvnr solution. don't forget to add preventDefault.

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
