### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by robmcvey** [defunkt/jquery-pjax#644]
Someone with iOS10 already might want to test in Safari. 

We've had to remove pjax completely, seems `pjax:complete` is never called.

Will continue to debug and update if I can.

**Comment by staabm** [comment]
have to test that right now, thx for the hint

**Comment by tm1000** [comment]
It won't work because $.support.pjax runs this
`
!navigator.userAgent.match(/((iPod|iPhone|iPad).+\bOS\s+[1-4]\D|WebApps\/.+CFNetwork)/)`

Which fails on iOS 10. is this project dead? I will do a pull request against it but seems like this is dead?

**Comment by tm1000** [comment]
I believe changing said line to this will work...

`navigator.userAgent.match(/((iPod|iPhone|iPad).+\bOS\s+[1-4]\D|WebApps\/.+CFNetwork)/)
`

**Comment by mikesheppard** [comment]
Yes I've tested with IOS 10 too with Safari and Chrome and confirmed it's breaking.

**Comment by mislav** [comment]
Thanks for the comments. In which way is this broken?

**Comment by joexanderson** [comment]
I have been using Pjax in my projects and have had no issues with iOS 10; in Chrome and Safari. However, I am only listening for `pjax:end`. If you try that does it work again?

**Comment by gregormck** [comment]
I had the same issue but updated to the most recent version of PJAX and now it works fine. We use pjax:complete too. @robmcvey are you on the latest version (last updated 16 Sep 15)?

**Comment by robmcvey** [comment]
@gregormck I don't think so, no. Thanks for the heads-up though.  

We've opted to remove pjax completely due to the lack of activity and hanging PRs. 

I'll leave the issue open for a core member to close if indeed it's a non-issue in most recent version.

**Comment by joexanderson** [comment]
@robmcvey Yes, and unfortunately GitHub has taken the project internally and made some incompatible changes to it. So it's not likely we'll see any changes soon.

**Comment by gregormck** [comment]
@robmcvey What did you replace it with? I might do the same...

**Comment by mislav** [comment]
@robmcvey Do you have any tangible evidence that jquery-pjax is broken in iOS 10?

**Comment by tm1000** [comment]
Updating the library to the newest in this repo fixed the issue as well. it was a simple user-agent fix they did a while back that would match iOS 10.x as iOS 1.x

**Comment by shigg1120** [comment]
@tm1000 
This is a noobish question but where is the newest repo located? Can you drop a link here?

Or. are you talking about pjax 1.9.6?

**Comment by joexanderson** [comment]
@shigg1120 He meant the latest release in this repo. The current Pjax repo is a private one within GitHub as they're now using it on site.

**Comment by tm1000** [comment]
I ended up removing pjax from my project all together. The poor support from github on project reminds me of the poor support twitter gave typeahead. I fail to see why it's so hard to push a new release with simple fixes like this (that already exist in the code!)

**Comment by mislav** [comment]
A new version of jquery-pjax is now tagged: https://github.com/defunkt/jquery-pjax/releases/tag/v2.0.0

Let us know if there are further iOS problems!
