### ISSUE TITLE
On same link doesn't work reload by default

### ISSUE THREAD

**Issue by tasmaniski** [defunkt/jquery-pjax#646]
If you implement for eg. on every click 

`$.pjax.click(event, {container: $("#content")});`

In situation when from URL  `/old-page` click and go to  `/new-page` 
and after that click 5 times the same link `/new-page` the page will load 5 times, what is expected. 
But on back button you need to go 5 times to  reach out the `/old-page` page. 

Of Course you can bypass the situation in manual decision, but it should be a normal situation.
My code: 

```
// back button doesn't work as supposed on same link
//$(document).pjax('a', '#content');

$(document).on('click', 'a', function (event) {
    // old way, back button doesn't work as supposed on same link
    //$.pjax.click(event, {container: $("#content")});

    // manual triger req. or reload
    var uri = window.location.pathname+window.location.search;
    var url = $(this).attr("href");
    if(uri != url){
        $.pjax.click(event, {container: $("#content")});
    }
    else{
        $.pjax.reload('#content')
    }    

    event.preventDefault();
});
```

**Comment by tasmaniski** [comment]
Alternatively you can use: 

Pjax option:
replace: true	 -  replace URL without adding browser history entry.

**Comment by mislav** [comment]
This is a known problem, but is not something that we're motivated to fix. If you do come up with a fix for repeated duplicate history entries, please send us a pull request. Thank you!
