### ISSUE TITLE
pjax.js doesn't load js files in footer section

### ISSUE THREAD

**Issue by nkuldip** [defunkt/jquery-pjax#648]
Hello,

I tried to do my best with this wonderfull script but i'm not sure i did well. i run all my scripts before </body>, jQuery first, Modernizr and then PJAX

here is what i do for running scripts :
```

$(function(){
	        // pjax
	        $(document).pjax('a', 'body')
        })
          $(document).ready(function(){
        	 // does current browser support PJAX
	          if ($.support.pjax) {
	          $.pjax.defaults.timeout = 3000; // time in milliseconds
	          }
          
          });
```

everything works perfectly but when PJAX load content that time datepicker and other features not work. 

If someone can help me, it would be nice :)
Thanks a lot :)

**Comment by seanthepottingshed** [comment]
Maybe try initialising your datepicker after pjax:end.

**Comment by seanthepottingshed** [comment]
`$(document).on('pjax:complete', function() {
  // Call JS here
})`

**Comment by nkuldip** [comment]
I have many js not just inline js so how can i call?

**Comment by Panoply** [comment]
Call your plugins in the `#pjax-container`not outside the container.
