### ISSUE TITLE
Help to delay the pjax

### ISSUE THREAD

**Issue by Overtrainer** [defunkt/jquery-pjax#649]
Hi, i use the pjax and have a problem
I need to stop for some sec the pjax-transition on the other page, but i dont know how
I tried to change the timeout option, add setTimeout, connect the php url and register there sleep() - NOTHING!
Please, help me

**Comment by mislav** [comment]
Sorry, pjax right now doesn't offer any functionality for dealing with transitions and delaying. See related discussion here: https://github.com/defunkt/jquery-pjax/issues/498#issuecomment-95509759. Some workarounds were suggested, but they are very complicated and brittle, and ultimately I wouldn't suggest them.

In short: pjax + page transitions = 🙅 .
