### ISSUE TITLE
$.pjax({url: url, container: '.container'}) bug

### ISSUE THREAD

**Issue by ysysdzz** [defunkt/jquery-pjax#650]
$('.container').delegate('.ui-add-btn', 'click', function () {
		var url = $(this).data('link'); //url is /datainsight/dashboard/toAdd
		$.pjax({url: url, container: '.container'})
});
when i click that button  is  not  local refresh。 all page refresh

**Comment by mislav** [comment]
I think you will need to add a `return false` after `$.pjax` call to prevent the original click event from activating the link/form submit.

**Comment by ysysdzz** [comment]
@mislav I've tried, but still cannot work well

**Comment by ysysdzz** [comment]
@mislav thank you!

**Comment by luger1990** [comment]
@ysysdzz did it works for u? it does not work for me
