### ISSUE TITLE
[jquery3] Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by creativeprogramming** [defunkt/jquery-pjax#652]
Is this plugin tested with jQuery 3.1.1? any plan to support it?

**Comment by olemoign** [comment]
https://github.com/defunkt/jquery-pjax/issues/634

**Comment by tm1000** [comment]
It's not updated at all. There is a member from github on here but as much as we've all pushed there isn't any movement.

But good news! You can use jquery migrate and pjax will work just fine! https://code.jquery.com/jquery-migrate-3.0.0.js

**Comment by lydell** [comment]
> You can use jquery migrate and pjax will work just fine!

Except that the back and forward buttons won’t work unless you add an extra script: https://github.com/defunkt/jquery-pjax/issues/638#issuecomment-259090560

**Comment by WenTao-Love** [comment]
greate

**Comment by mislav** [comment]
Closing as duplicate.
