### ISSUE TITLE
How to integrate this PJAX with Material Design template and jquery plugin without any conflicts?

### ISSUE THREAD

**Issue by blackzero080** [defunkt/jquery-pjax#656]
I've been using pjax to load page like this:
`$(document).pjax('[data-pjax] a, a[data-pjax]', '#pjax-container');`

But after page loaded, some Material Design components could not be displayed properly (Textfield label overlaps with input value) and some jquery plugins like select2, datepicker could not work properly too

How to integrate this PJAX with Material Design template and jquery plugin without any conflicts?

**Comment by mislav** [comment]
Sorry, I'm not familiar with Material Design components.

jquery-pjax works on its own. If there is a conflict with other libraries in your project, I hope you'll be able to resolve it.
