### ISSUE TITLE
I want to load all the script again when pjax is end , How it is possible?

### ISSUE THREAD

**Issue by chiragsatapara** [defunkt/jquery-pjax#658]
Hello,

In my application  there is a different js file for each pages , i want to load that file into the pjax, How it is possible ? Without reloading that js files my pages is not working,  can any one help me to solve this issue asap.

**Comment by fonmaxfon** [comment]
stop dives houk

**Comment by fari-99** [comment]
CMIIW, but I think you can't do that with this pjax. I have the same problem like @chiragsatapara, and what I'm doing has i put **all** my script into the main container so it will load all of the scripts and you can check the element for your particular page to load a function for that page.

**Comment by jiangyongyuan** [comment]
here is my solution ,
1.write by require-js . move the script element inside the container  , so the pjax will load and run the js at the first time .
2.change the js , add pjax:complete callback in each model js , let the callback to run the js again at the second time .
require(['constant', 'site'], function (Constant, Site) {
    var modelHref = window.location.href;
    var run = function(){
        modelHref = window.location.href;
         /** real code here */
    }
    run();
    $(document).on('pjax:complete', function() { 
        if( modelHref == window.location.href ){
            run();
        }
    });
});

**Comment by mislav** [comment]
@fari-99's suggestion is the correct workaround.
