### ISSUE TITLE
 Frequent page switching, js error

### ISSUE THREAD

**Issue by evildancer** [defunkt/jquery-pjax#659]
Js in the last page is not the implementation of the completion, I switched to the next page, resulting in js error, this problem is a solution?

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
