### ISSUE TITLE
tag a new release

### ISSUE THREAD

**Issue by staabm** [defunkt/jquery-pjax#664]
could you please tag a new release...? 

our app relies on the master branch for longer then a year because there are commits from 2015 which are not part of a tagged release yet :-/

**Comment by johann-abraham** [comment]
+1

**Comment by acs-ferreira** [comment]
Is this project maintained at all?

**Comment by mislav** [comment]
https://github.com/defunkt/jquery-pjax/releases/tag/v2.0.0
