### ISSUE TITLE
is jquery-pjax alive in 2017? 

### ISSUE THREAD

**Issue by maliknur** [defunkt/jquery-pjax#666]
Looks like is not maintained anymore, if last commit was done in late 2015. and having 37 pull request hanging on, and so many open issues.
Maybe maintainer needs change to someone who has more time for supporting it?
It's so  weird and sad to see such nice library with 14K stars to be without support...

**Comment by olemoign** [comment]
@mislav discussed this in issue #638.

**Comment by olemoign** [comment]
Question is, would anybody be willing to help maintain ? I could be interested, but only if we were a few maintainers.

**Comment by mislav** [comment]
Yes, there's already an open issue about the maintenance status of this library, so I'm closing this as duplicate.

We don't know if anybody would step up to be a maintainer. What we do need right now is a far lesser commitment: to simply ensure that this library works with the latest version of jQuery. There are already some pull requests and patches, but they need to be reviewed and modified to pass the CI suite.
