### ISSUE TITLE
Just a question to see if pjax is suitable for my needs

### ISSUE THREAD

**Issue by petrospap** [defunkt/jquery-pjax#668]
What I want to achieve is

1) From page A with ajax, load and append data to .pjax-static-div
2) Go to page B and keep without reload or lose .pjax-static-div and his data

Can do this jquery-pjax?

If yes can anyone provide any example??

Thank you

**Comment by olemoign** [comment]
Could you please describe your case in more details ? I don't understand your question.

**Comment by petrospap** [comment]
I wand to load data to one div with ajax, 
and when i go to other page/s to have this data in to the div without call again the ajax query

**Comment by olemoign** [comment]
No, pjax doesn't do this.

**Comment by mislav** [comment]
What pjax does is enables replacing page content within a container element without reloading the whole page, while keeping sure the URL is updated.

What pjax doesn't do is everything else.
