### ISSUE TITLE
Community-managed fork

### ISSUE THREAD

**Issue by olemoign** [defunkt/jquery-pjax#669]
Hi guys, 

I use pjax in production, so I'm willing to do work on it. I have created a PR for jQuery3 support a month ago, which @mislav who I suppose is the only maintainer here, hasn't yet replied too. 
I'm getting tired of this, the first talks about this subject where 8 months ago. And numerous offers were made to increase the number of maintainers, without effect.
Who here, would be willing to help me make an active fork of this project ? I don't want to do it on my own (because it leads to situations like we have now), at least 3 people would be nice.

Cheers.

PS @mislav : I don't blame you for the situation. You've already given a lot, and I thank you for this. You don't have the time, I understand this. But then please accept it and work with the community to find a solution.

**Comment by tm1000** [comment]
Github should allow @mislav to add other maintainers to the project. The fact that github is just allowing it to turn into abandonware is just baffling. This story is similar to twitter's typeahead. 

http://getpostdelete.com/how-not-to-write-an-api.html

**Comment by ui4j** [comment]
Good sugestion, i also need JQuery 3 support for production. Please share your work with us.

**Comment by olemoign** [comment]
#665

**Comment by Enalmada** [comment]
Based on stars and an assumption that many multiples of people use something without staring, his is a growing github customer satisfaction issue for tens of thousands of customers that know github has a relationship with this repo.  Please github, just donate enough time to this to figure out how to add some maintainers or point to the right community managed fork.

**Comment by mislav** [comment]
Thanks for the discussion, everyone! Open source works in a way that anyone can start a fork for whatever reason and whenever they like. You are welcome to do this. I'm just closing this out since the original problem (incompatibility with latest jQuery) is now solved.
