### ISSUE TITLE
Pjax with ASP.NET Web Forms

### ISSUE THREAD

**Issue by SkyKurosaki** [defunkt/jquery-pjax#671]
I am trying to create an audio streaming website, allowing the user to play music while at the same time browse the site. But unfortunately there are no tutorials for such. Can you make a working example of how one gets to start using pjax with asp.net web forms. Thanks.

**Comment by mislav** [comment]
Sorry, I don't have experience with asp.net web forms. It sounds like you should be doing a more manual approach for your site and not use pjax, which is intended for simpler use cases.
