### ISSUE TITLE
Javascript not working unless do reload to page

### ISSUE THREAD

**Issue by mustafaabduljalil** [defunkt/jquery-pjax#677]
I'm using pjax and when click on button content change but to run javascript  i should reload page ? can anyone help me ?

**Comment by mislav** [comment]
We don't offer support for integrating pjax into web pages. Unless you need to report something that looks like a bug in our library, this is not the right place to ask question about how to write JS for your site. However, please familiarize yourself with the concept of reinitializing page plugins after content has changed via pjax navigation: https://github.com/defunkt/jquery-pjax#advanced-configuration
