### ISSUE TITLE
Pjax: custom object with form data 

### ISSUE THREAD

**Issue by vikramktechhighway** [defunkt/jquery-pjax#690]
I want to post a form along with my custom object.

var myData = JSON.stringify(values);
    console.log(myData);
 $.pjax({
    type: 'POST',
    url: url,
    container:'#' + pjax_id,
    data: myData,
    dataType: 'application/json'
  });
custom data is not posted along with formdata.

**Comment by RichardTMiles** [comment]
concider using the pjax.submit method and adding your data to a field in the forum 

```JS
 $(document).on('submit', 'form[data-pjax]', (event) => {
        $(selector).hide();
        $.pjax.submit(event, selector)
    });
```

**Comment by vikramktechhighway** [comment]
@RichardTMiles Thank you
