### ISSUE TITLE
PJAX + DOM Hard Load

### ISSUE THREAD

**Issue by tetrahydra** [defunkt/jquery-pjax#692]
I need to change/filter some contents before that it is being displayed, so I use this DOM method.

```
$doc_content = new DOMDocument();
$doc_content->loadHTML('<!DOCTYPE html><html><meta http-equiv="content-type" content="text/html; charset=utf-8"><body>' . $content_cms . '</body></html>');
```

On every page that uses this method PJAX will hard (force) load the page. When I remove this process, PJAX works fine.

Is there any work around for this issue?

**Comment by staabm** [comment]
Cant you just filter the ajax contents with jquery means?

**Comment by tetrahydra** [comment]
we have to filter inappropriate word using another database and resize photos or disabled photos from being displayed. jquery will slow down the process as all of the words need to be sent along with the output.

**Comment by staabm** [comment]
Hmm ok, didnt got what you said intially. Why do you render a document incl. Doctype etc?

**Comment by tetrahydra** [comment]
I tried like this before:
```
$doc_content->loadHTML($content_cms);
```
and this function doesnt work

```
$imgs = $doc_content->getElementsByTagName('img');
```

that loadHTML requires html rendering.

**Comment by staabm** [comment]
I still dont get what you are doing and why. Usually you would just return/render your $cms_content without this javascript loadHtml thing.

Could you provide more information, why you need this additional javascript?

**Comment by tetrahydra** [comment]
the DOM and loadHTML are PHP code.

1. Get all non-permitted words from mysql database.
2. Filter the word from $cms_content.
3. Return the filtered content.

1. Get all IMG tags in $cms_content
2. Check the filename against mysql database
3. If not-permitted for display, remove the tag.
4. Return filtered content.

**Comment by tetrahydra** [comment]
I have it solved.

```
$content_cms = preg_replace('~<(?:!DOCTYPE|/?(?:html|head|body))[^>]*>\s*~i', '', $content_cms);
```
