### ISSUE TITLE
Link to do just as browser back button

### ISSUE THREAD

**Issue by ZalemCitizen** [defunkt/jquery-pjax#710]
Hello there, 

Maybe I didn't notice a simple way to do so, but I need to make a link that act just as a a click on the browser back button which is restore the last pjax state on container and restore the previous URL.

Is there a way to do so ?

**Comment by ZalemCitizen** [comment]
Forget it : guess I had an event bubbling situation in my history.back() tests..
history.back() is the simple way to do so.

**Comment by urielQ** [comment]
sorry,I don't know about jquery-pjax
